# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from entidades.models import Gauser_extra, Ronda, Subentidad


class Dimension(models.Model):
    abrev = models.CharField("Abreviatura", max_length=7)
    nombre = models.CharField("Nombre de la dimensión", max_length=50)
    descripcion = models.TextField("Descripción de la dimensión")

    def __unicode__(self):
        return u'%s -- %s' % (self.abrev, self.nombre)


SECTORES = (('NODOCENTES', 'No docentes'), ('DOCENTES', 'Docentes'), ('FAMILIAS', 'Familias/Tutores legales'),
            ('ALUMNOS', 'Alumnos/as'))


class Pregunta(models.Model):
    dimension = models.ForeignKey(Dimension, on_delete=models.CASCADE)
    sector = models.CharField("Sector al que va destinada", max_length=15, choices=SECTORES)
    pregunta = models.TextField("Pregunta")

    class Meta:
        ordering = ['dimension']

    def __unicode__(self):
        return u'%s %s (%s)' % (self.dimension.abrev, self.sector, self.pregunta[:40])


class Encuesta(models.Model):
    ronda = models.ForeignKey(Ronda, on_delete=models.CASCADE)
    sector = models.CharField("Sector al que va destinada", max_length=15, choices=SECTORES)
    subentidad = models.ForeignKey(Subentidad, on_delete=models.CASCADE, blank=True, null=True)

    def __unicode__(self):
        return u'%s (%s)' % (self.sector, self.ronda)


RESPUESTAS = ((0, 'NS/NC'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'),
              (9, '9'), (10, '10'))


class Respuesta(models.Model):
    encuesta = models.ForeignKey(Encuesta, on_delete=models.CASCADE)
    ge = models.ForeignKey(Gauser_extra, on_delete=models.CASCADE)
    pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
    respuesta = models.IntegerField("Grado de cumplimiento", max_length=15, choices=RESPUESTAS)

    def __unicode__(self):
        return u'%s -- %s -- %s (%s)' % (self.encuesta, self.ge, self.pregunta, self.respuesta)


Alumnos = [('ALUMNOS', 'LIDE', 1, 'El Equipo Directivo escucha a la Junta de delegados y conoce los problemas.'),
           ('ALUMNOS', 'LIDE', 1,
            'El Equipo Directivo nos anima a participar en las actividades que se realizan en el Centro.'),
           ('ALUMNOS', 'LIDE', 1,
            'El Equipo Directivo nos motiva y potencia nuestras ganas de  aprender y nuestro interés.'),
           ('ALUMNOS', 'PLAN', 2, 'Conozco el Proyecto Educativo del Centro y para qué sirve.'),
           ('ALUMNOS', 'PLAN', 2,
            'Nuestra presencia en el Consejo Escolar es activa y  participamos en la toma de decisiones.'),
           ('ALUMNOS', 'PLAN', 2, 'Los alumnos recibimos información suficiente sobre el funcionamiento del Centro.'),
           ('ALUMNOS', 'GERE', 3, 'Las instalaciones del Centro están bien acondicionadas.'),
           ('ALUMNOS', 'GERE', 3, 'Las aulas son cómodas y agradables.'),
           ('ALUMNOS', 'GERE', 3, 'Las aulas están bien equipadas con materiales didácticos.'),
           ('ALUMNOS', 'GERE', 3,
            'El  horario y organización de la biblioteca del Centro se  adapta a nuestras necesidades.'),
           ('ALUMNOS', 'GERE', 3, 'El servicio de comedor (si es que existe y lo utiliza) es bueno.'),
           ('ALUMNOS', 'GERE', 3, 'El servicio de transporte (si es que existe y lo utiliza) es bueno.'),
           ('ALUMNOS', 'GERE', 3, 'En el Centro nos sentimos seguros y protegidos ante posibles accidentes.'),
           ('ALUMNOS', 'GERE', 3,
            'El Centro dispone de un plan y ruta de evacuación para urgencias conocido por el alumnado.'),
           ('ALUMNOS', 'GERE', 3, 'El patio del Centro está bien cuidado.'),
           ('ALUMNOS', 'GERE', 3, 'El alumnado ayuda a mantener las instalaciones en buen estado.'),
           ('ALUMNOS', 'PRED', 4, 'Los temas que estudio me parecen, en general, interesantes y útiles.'),
           ('ALUMNOS', 'PRED', 4, 'El profesorado me anima a aprender y a motivarme.'),
           ('ALUMNOS', 'PRED', 4, 'El profesorado se hace respetar.'),
           ('ALUMNOS', 'PRED', 4, 'El profesorado hace que se respeten las normas de convivencia.'),
           ('ALUMNOS', 'PRED', 4, 'El profesorado se ocupa por los alumnos que tienen problemas.'),
           ('ALUMNOS', 'PRED', 4, 'El profesorado reconoce y valora si me esfuerzo.'),
           ('ALUMNOS', 'PRED', 4, 'La forma de dar clase del profesorado me motiva para aprender.'),
           ('ALUMNOS', 'PRED', 4, 'Se llevan a cabo actividades fuera del centro (visitas a empresas, museos, etc.).'),
           ('ALUMNOS', 'PRED', 4, 'Dichas actividades mejoran mi aprendizaje.'),
           ('ALUMNOS', 'PRED', 4, 'Conocemos adecuadamente lo que nos van a exigir en cada asignatura.'),
           (
           'ALUMNOS', 'PRED', 4, 'Se analizan los resultados de evaluación con el grupo de alumnos al que pertenezco.'),
           ('ALUMNOS', 'PRED', 4, 'Estoy bien informado de mis resultados académicos y de mi rendimiento.'),
           ('ALUMNOS', 'PRED', 4,
            'Se informa adecuadamente a nuestras familias de muestra marcha en los estudios y de nuestros problemas en el Centro.'),
           ('ALUMNOS', 'CLES', '5', 'La convivencia en el Centro es buena.'),
           ('ALUMNOS', 'CLES', '5', 'Cuando existe un conflicto, la dirección y el profesorado intentan solucionarlo.'),
           ('ALUMNOS', 'CLES', '5', 'Considero que hay una buena disciplina en el centro que favorece la convivencia.'),
           ('ALUMNOS', 'PART', '6', 'Participo en las actividades de mi Centro.'),
           ('ALUMNOS', 'PART', '6', 'En el Centro se atienden correctamente las quejas y peticiones de los alumnos.'),
           ('ALUMNOS', 'PART', '6', 'Participo en las actividades extraescolares del Centro.'),
           ('ALUMNOS', 'RESU', '7', 'Estoy satisfecho con el Equipo Directivo de mi Centro.'),
           ('ALUMNOS', 'RESU', '7', 'Estoy satisfecho con las actividades que se planifican en el Centro.'),
           ('ALUMNOS', 'RESU', '7',
            'Estoy satisfecho con los recursos e instalaciones que ofrece el Centro y su aprovechamiento.'),
           ('ALUMNOS', 'RESU', '7', 'Estoy satisfecho con mi aprendizaje en el Centro.'),
           ('ALUMNOS', 'RESU', '7', 'Estoy a gusto con mis compañeros.'),
           ('ALUMNOS', 'RESU', '7', 'Estoy satisfecho con mí de participación en la vida del Centro.'),
           ('ALUMNOS', 'RESU', '7', 'Tengo buenos profesores.'),
           ('ALUMNOS', 'RESU', '7', 'Recomendaría a un amigo que viniera a estudiar a este Centro.')]

nodocentes = [
    ('NODOCENTES', 'LIDE', 1, 'El Equipo Directivo informa a todo el personal no docente de los objetivos del Centro.'),
    ('NODOCENTES', 'LIDE', 1, 'Se implica al personal no docente en los procesos de mejora.'),
    ('NODOCENTES', 'LIDE', 1,
     'El Equipo Directivo reconoce las iniciativas de mejora y el  trabajo  bien hecho del personal no docente.'),
    ('NODOCENTES', 'PLAN', 2,
     'Se tiene conciencia de la función y orientación que debe seguir el Centro en su servicio a la sociedad.'),
    ('NODOCENTES', 'PLAN', 2,
     'La Memoria Anual recoge las propuestas de mejora realizadas  por  el personal no docente.'),
    ('NODOCENTES', 'PLAN', 2,
     'Se asiste a las reuniones del Consejo Escolar debidamente  informados para poder opinar y participar en la toma de decisiones.'),
    ('NODOCENTES', 'PERS', '3',
     'El personal no docente trabaja con vocación y dedicación  contribuyendo a lograr los objetivos del Centro.'),
    ('NODOCENTES', 'PERS', '3',
     'El personal no docente tiene claras cuáles son sus responsabilidades en el logro de la mejora del Centro.'),
    ('NODOCENTES', 'PERS', '3',
     'El sistema empleado para conocer el grado de satisfacción de las personas que trabajan en el Centro es adecuado.'),
    ('NODOCENTES', 'PERS', '3', 'La seguridad del Centro y su estado de conservación son adecuados.'),
    ('NODOCENTES', 'PERS', '3', 'El Plan de Evacuación es conocido y practicado suficientemente.'),
    ('NODOCENTES', 'PERS', '3', 'La limpieza y cuidado de los espacios del Centro son satisfactorios.'),
    ('NODOCENTES', 'PERS', '3', 'Los accesos al Centro y la movilidad en su interior son adecuados.'),
    ('NODOCENTES', 'PERS', '3', 'Los horarios del personal no docente están adaptados a las necesidades del Centro.'),
    ('NODOCENTES', 'OGPR', 4,
     'La planificación y distribución de tareas entre los diferentes profesionales del personal no docente del Centro es adecuada.'),
    ('NODOCENTES', 'CLES', 5,
     'La aplicación del Reglamento de Organización y Funcionamiento contribuye  eficazmente a resolver problemas de convivencia.'),
    ('NODOCENTES', 'CLES', 5,
     'En la elaboración y revisión del Reglamento de Organización y Funcionamiento se tienen en cuenta las aportaciones del personal no docente.'),
    ('NODOCENTES', 'CLES', 5, 'El procedimiento de resolución de conflictos es suficientemente eficaz en el Centro.'),
    ('NODOCENTES', 'PART', 6,
     'EL personal no docente participa con interés en la mejora de la actividad y la vida del Centro.'),
    ('NODOCENTES', 'PART', 6,
     'Se atienden debidamente las sugerencias o reclamaciones formuladas por el personal no docente.'),
    ('NODOCENTES', 'PART', 6, 'Estoy satisfecho con la labor del Equipo Directivo.'),
    ('NODOCENTES', 'PART', 6, 'Estoy satisfecho con la planificación que realiza el Centro.'),
    ('NODOCENTES', 'PART', 6, 'Estoy satisfecho con la organización de los procesos que desarrolla el Centro.'),
    ('NODOCENTES', 'PART', 6, 'El clima de convivencia en el Centro es satisfactorio.'),
    ('NODOCENTES', 'PART', 6, 'Estoy satisfecho con las posibilidades de participación en la vida del Centro.'),
    ('NODOCENTES', 'PART', 6, 'Recomendaría a un amigo que viniera a trabajar a este Centro.'),
    ('NODOCENTES', 'REEN', 7, 'Estoy satisfecho de la imagen que ha conseguido el Centro en la localidad.')]

docentes = [('DOCENTES', 'LIDE', '1',
             'El Equipo Directivo se asegura de que toda la Comunidad Educativa esté informada de los objetivos del Centro.'),
            ('DOCENTES', 'LIDE', '1',
             'El Equipo Directivo anima a la Comunidad Educativa a participar en todos en los procesos de mejora.'),
            ('DOCENTES', 'LIDE', '1',
             'El Equipo Directivo reconoce las iniciativas de mejora de los diferentes  miembros de la Comunidad Educativa.'),
            ('DOCENTES', 'LIDE', '1', 'El Equipo Directivo se preocupa de proyectar el Centro al exterior.'),
            ('DOCENTES', 'LIDE', '1',
             'Las relaciones y el clima de convivencia permiten ejercer conductas de liderazgo.'),
            ('DOCENTES', 'LIDE', '1',
             'Existe voluntad y compromiso suficiente entre los miembros de la  Comunidad Educativa para asumir tareas de liderazgo.'),
            ('DOCENTES', 'PLAN', '2',
             'La Comunidad Educativa tiene conciencia de los fines y objetivos que tiene el Centro en su labor de servicio a la sociedad.'),
            ('DOCENTES', 'PLAN', '2',
             'Las necesidades planteadas por el entorno se analizan y recogen adecuadamente en el Proyecto Educativo y Programaciones.'),
            ('DOCENTES', 'PLAN', '2',
             'En la planificación se recogen las expectativas y propuestas de los distintos sectores de la Comunidad Educativa.'),
            ('DOCENTES', 'PLAN', '2',
             'En  el  PEC  están  definidos  adecuadamente  los  objetivos  principales  que  se  deben conseguir por el Centro.'),
            ('DOCENTES', 'PLAN', '2',
             'Las líneas de mejora planteadas responden a un adecuado diagnóstico de la situación.'),
            ('DOCENTES', 'PLAN', '2', 'EL Plan de Acción Tutorial responde a las necesidades del alumnado.'),
            ('DOCENTES', 'PLAN', '2',
             'Se realiza una adecuada aplicación y desarrollo de la Programación General Anual.'),
            ('DOCENTES', 'PLAN', '2',
             'El Plan de Mejora recoge adecuadamente las necesidades de la Comunidad Educativa.'),
            ('DOCENTES', 'PLAN', '2', 'La Memoria es un instrumento eficaz para mejorar como centro.'),
            ('DOCENTES', 'PLAN', '2',
             'El Equipo Directivo se implica en la implantación de los procesos de mejora acordados para el Centro.'),
            ('DOCENTES', 'PLAN', '2',
             'El Equipo Directivo se ocupa de que se lleven a cabo los acuerdos  de los diferentes órganos de participación y coordinación del Centro.'),
            ('DOCENTES', 'PLAN', '2',
             'Los Departamentos Didácticos y órganos de coordinación presentan iniciativas en proyectos de innovación, formación e investigación.'),
            ('DOCENTES', 'PLAN', '2',
             'El Departamento de Orientación colabora eficazmente en la detección de problemas de aprendizaje y ayuda en la adaptación curricular.'),
            ('DOCENTES', 'PLAN', '2',
             'El Claustro evalúa los resultados del centro y propone iniciativas para su mejora.'),
            ('DOCENTES', 'PLAN', '2',
             'La Comisión de Coordinación Pedagógica establece las directrices y criterios para desarrollar el Proyecto Educativo de Centro y la PGA.'),
            ('DOCENTES', 'PLAN', '2',
             'Los representantes del profesorado en el Consejo Escolar informan suficientemente de lo tratado en las reuniones.'),
            ('DOCENTES', 'PERS', '3', 'El profesorado trabaja con profesionalidad, dedicación y motivación.'),
            ('DOCENTES', 'PERS', '3',
             'Existe una cultura de centro basada en valores, estilos y pautas de comportamiento.'),
            ('DOCENTES', 'PERS', '3',
             'Los profesores reciben la formación necesaria para que actualicen sus conocimientos y competencias.'),
            ('DOCENTES', 'PERS', '3',
             'El sistema empleado para conocer el grado de satisfacción de las personas que trabajan en el Centro es adecuado.'),
            ('DOCENTES', 'GERE', '4', 'La distribución del presupuesto responde a la planificación del Centro.'),
            ('DOCENTES', 'GERE', '4', 'La utilización de los recursos materiales se gestiona adecuadamente.'),
            (
            'DOCENTES', 'GERE', '4', 'las instalaciones son adecuadas para las necesidades de la Comunidad Educativa.'),
            ('DOCENTES', 'GERE', '4', 'Las aulas reúnen las condiciones adecuadas.'),
            ('DOCENTES', 'GERE', '4',
             'El equipamiento didáctico de las aulas se usa adecuadamente  para  el logro de los objetivos.'),
            ('DOCENTES', 'GERE', '4', 'El equipamiento informático es adecuado a las necesidades docentes.'),
            ('DOCENTES', 'GERE', '4',
             'La biblioteca está adecuada a las necesidades derivadas de la actividad docente.'),
            ('DOCENTES', 'GERE', '4',
             'La dotación y estado de los espacios exteriores es adecuada al  tipo de actividades desarrolladas.'),
            ('DOCENTES', 'GERE', '4',
             'Se realiza una gestión eficaz de la prevención de riesgos, la seguridad y las emergencias.'),
            ('DOCENTES', 'GERE', '4',
             'Existe una adecuada implicación de todos en el mantenimiento y cuidado de las instalaciones y recursos.'),
            ('DOCENTES', 'GERE', '4',
             'El Centro coopera suficientemente con los agentes del entorno en  la realización de diversas actividades didácticas, aprovechando los recursos que ofrecen.'),
            ('DOCENTES', 'GERE', '4', 'El Centro aprovecha las experiencias positivas de otros Centros.'),
            ('DOCENTES', 'OGPR', '5', 'La distribución de funciones y tareas en el Centro es adecuada.'),
            ('DOCENTES', 'OGPR', '5',
             'Los indicadores que utiliza el Centro para evaluar el grado de consecución de  los objetivos son eficaces.'),
            ('DOCENTES', 'OGPR', '5',
             'Los sistemas de seguimiento y evaluación para cada proceso están correctamente definidos.'),
            ('DOCENTES', 'OGPR', '5',
             'Los resultados de la auto-evaluación y revisión de procesos sirven para fijar objetivos de mejora que incrementan la eficacia del Centro.'),
            ('DOCENTES', 'PRED', '6',
             'Existe una planificación coordinada por departamentos con  objetivos, metodología y criterios y procedimientos de evaluación compartidos.'),
            (
            'DOCENTES', 'PRED', '6', 'El alumnado conoce adecuadamente los criterios de evaluación y de calificación.'),
            ('DOCENTES', 'PRED', '6',
             'Los contenidos tienen en cuenta las necesidades de la realidad social del entorno.'),
            ('DOCENTES', 'PRED', '6',
             'El profesorado se preocupa de motivar motiva a los alumnos para aprender y participar en las actividades del Centro.'),
            ('DOCENTES', 'PRED', '6', 'Hay un clima de orden y respeto mutuo en el aula.'),
            ('DOCENTES', 'PRED', '6',
             'Se asume la innovación de la metodología didáctica como una línea de mejora importante.'),
            ('DOCENTES', 'PRED', '6',
             'El profesorado tiene autonomía para combinar las metodologías didácticas que más se adapten a su grupo.'),
            ('DOCENTES', 'PRED', '6',
             'Se organizan actividades complementarias adecuadas que ayudan al aprendizaje: visitas a empresas, museos, proyecciones de vídeo, etc.'),
            ('DOCENTES', 'PRED', '6',
             'Se tiene en cuenta la evaluación inicial del alumno para adaptar la programación de cada unidad didáctica a sus características.'),
            ('DOCENTES', 'PRED', '6',
             'Se analizan adecuadamente los resultados de la evaluación con el grupo de alumnos.'),
            ('DOCENTES', 'PRED', '6',
             'Se establecen cauces adecuados para comunicar e informar a los alumnos y familias de su situación escolar.'),
            ('DOCENTES', 'PRED', '6',
             'Los tutores se coordinan con el equipo educativo de su grupo y con el Departamento de Orientación para hacer un seguimiento del aprendizaje de los alumnos.'),
            ('DOCENTES', 'PRED', '6', 'El tutor mantiene una comunicación regular y fluida con las familias.'),
            ('DOCENTES', 'CLES', '7',
             'La información que reciben las familias de las faltas de asistencia y de los problemas de relación consiguen que se impliquen en la mejora de la convivencia del Centro.'),
            ('DOCENTES', 'CLES', '7',
             'El Reglamento de Régimen Interior contribuye a la mejora de la convivencia en el Centro.'),
            ('DOCENTES', 'CLES', '7',
             'El Centro organiza actividades que favorezcan la creación de actitudes positivas.'),
            ('DOCENTES', 'CLES', '7',
             'Los procedimientos utilizados para analizar el clima del Centro son los adecuados.'),
            (
            'DOCENTES', 'CLES', '7', 'Estoy satisfecho con las medidas que se toman para mejorar el clima del Centro.'),
            ('DOCENTES', 'PART', '8', 'El profesorado participa en la gestión del Centro.'),
            ('DOCENTES', 'PART', '8',
             'El Profesorado se implica en la realización de actividades complementarias y extraescolares.'),
            ('DOCENTES', 'RESU', '9', 'Estoy satisfecho con el trabajo llevado a cabo por el Equipo Directivo.'),
            ('DOCENTES', 'RESU', '9', 'Estoy satisfecho con la planificación del Centro.'),
            ('DOCENTES', 'RESU', '9',
             'Estoy satisfecho con el desarrollo profesional que me aporta mi implicación en los planes de formación.'),
            ('DOCENTES', 'RESU', '9', 'Estoy satisfecho con los recursos del Centro y su aprovechamiento.'),
            ('DOCENTES', 'RESU', '9', 'Estoy satisfecho con la organización del Centro.'),
            ('DOCENTES', 'RESU', '9', 'Estoy satisfecho con la educación de los alumnos del Centro.'),
            ('DOCENTES', 'RESU', '9', 'Estoy satisfecho con mi nivel de implicación en el Centro.'),
            ('DOCENTES', 'RESU', '9',
             'Estoy satisfecho con el reconocimiento que recibo en el Centro, de los alumnos, de las familias.'),
            ('DOCENTES', 'RESU', '9',
             'Estoy satisfecho con la forma en que se lleva a cabo el proceso de mejora en el Centro.'),
            ('DOCENTES', 'RESU', '9',
             'Recomendaría a un amigo que viniera a trabajar impartiendo clases en este Centro.'),
            ('DOCENTES', 'REEN', '10',
             'La actividad del Centro contribuye a aumentar el bienestar en su entorno social incrementando su promoción social y educativa.'),
            ('DOCENTES', 'REEN', '10',
             'La actividad del Centro facilita el funcionamiento de otras instituciones (siguientes ciclos, centros sociales, empresas).'),
            ('DOCENTES', 'REEN', '10',
             'Se ha conseguido que el centro muestre una imagen positiva en su entorno próximo.'),
            ('DOCENTES', 'RECL', '11', 'Los resultados académicos del alumnado son satisfactorios.'),
            ('DOCENTES', 'RECL', '11', 'El nivel de habilidades sociales alcanzadas por el alumnado es satisfactorio.'),
            ('DOCENTES', 'RECL', '11',
             'El nivel de capacitación del alumnado para lograr una futura inserción laboral es satisfactorio.'),
            ('DOCENTES', 'RECL', '11',
             'El nivel de divulgación de nuestras Buenas Prácticas pedagógicas ha sido satisfactorio.')]

familias = [('FAMILIAS', 'LIDE', 1, 'El Equipo Directivo está abierto a las iniciativas de las familias.'),
            ('FAMILIAS', 'LIDE', 1, 'Se estimula la participación de las familias en el funcionamiento del Centro.'),
            ('FAMILIAS', 'LIDE', 1, 'El Proyecto Educativo y los objetivos del centro son conocidos por las familias.'),
            ('FAMILIAS', 'LIDE', 1,
             'Se potencia que las familias asuman responsabilidades y propongan iniciativas de mejora.'),
            ('FAMILIAS', 'LIDE', 1,
             'Las relaciones y el clima de convivencia en el Centro permiten aportar ideas e iniciativas y realizar peticiones.'),
            ('FAMILIAS', 'PLAN', 2, 'Se Reconocen las necesidades que plantea el entorno.'),
            ('FAMILIAS', 'PLAN', 2, 'Se definen anualmente los objetivos de mejora.'),
            ('FAMILIAS', 'PLAN', 2,
             'El Proyecto Educativo del Centro contribuye significativamente al mejor cumplimiento de la función del Centro.'),
            ('FAMILIAS', 'PLAN', 2, 'Se llevan a la práctica las líneas de mejora acordadas en el Consejo Escolar.'),
            ('FAMILIAS', 'GERE', 3, 'Las instalaciones están adecuadas a las necesidades de la Comunidad Educativa.'),
            ('FAMILIAS', 'GERE', 3, 'El espacio de atención a las familias está adecuado a las necesidades.'),
            ('FAMILIAS', 'GERE', 3, 'La biblioteca del centro cubre las necesidades de la Comunidad Educativa.'),
            ('FAMILIAS', 'GERE', 3, 'El servicio de comedor ofrece un servicio adecuado.'),
            ('FAMILIAS', 'GERE', 3, 'El servicio de transporte está adecuado a las necesidades de los alumnos.'),
            ('FAMILIAS', 'GERE', 3,
             'La dotación y estado de los espacios son adecuadas al tipo de actividades desarrolladas y a las necesidades del Centro.'),
            ('FAMILIAS', 'GERE', 3, 'Los sistemas de prevención son adecuados y se actualizan de forma correcta.'),
            ('FAMILIAS', 'GERE', 3,
             'Toda la Comunidad Educativa se implica en el mantenimiento y cuidado de las instalaciones y recursos.'),
            ('FAMILIAS', 'GERE', 3, 'Se facilita que las familias conozcan y tengan acceso a las instalaciones.'),
            ('FAMILIAS', 'GERE', 3,
             'Los contenidos que se imparten a los alumnos son adecuados para las necesidades y exigencias de su vida personal y laboral.'),
            ('FAMILIAS', 'GERE', 3, 'Se motiva a los alumnos a aprender y participar en las actividades del Centro.'),
            ('FAMILIAS', 'GERE', 3, 'Los alumnos reconocen y respetan la autoridad del profesor.'),
            ('FAMILIAS', 'GERE', 3,
             'El profesorado, en general, se ocupa de los problemas personales  y/o familiares que afectan a la integración de los alumnos.'),
            ('FAMILIAS', 'GERE', 3, 'El profesorado, en general, reconoce el esfuerzo de los alumnos.'),
            ('FAMILIAS', 'GERE', 3,
             'Se organizan actividades complementarias que ayudan y motivan al aprendizaje, como excursiones, visitas a museos, etc.'),
            ('FAMILIAS', 'GERE', 3,
             'Se conocen los criterios de evaluación de las asignaturas así como los procedimientos de evaluación y criterios de calificación que se aplican en cada asignatura.'),
            (
            'FAMILIAS', 'GERE', 3, 'El tutor informa adecuadamente a las familias de la situación escolar de su hijo.'),
            ('FAMILIAS', 'GERE', 3, 'Se realiza una tutoría eficaz para orientar la formación y solucionar problemas.'),
            ('FAMILIAS', 'GERE', 3, 'La comunicación con los profesores se posibilita cuando es necesario.'),
            ('FAMILIAS', 'GERE', 3, 'Los horarios de tutoría con las familias son adecuados y flexibles.'),
            ('FAMILIAS', 'CLES', 4,
             'Los sistemas de comunicación en el Centro contribuyen al  desarrollo  de unas buenas relaciones.'),
            ('FAMILIAS', 'CLES', 4, 'Los sistemas de participación contribuyen a la mejora de las relaciones.'),
            ('FAMILIAS', 'CLES', 4, 'El Reglamento de Régimen Interior contribuye a la convivencia en el Centro.'),
            ('FAMILIAS', 'CLES', 4,
             'La información que se da a las familias de las faltas de asistencia y  los problemas de convivencia es efectiva, para mejorar el clima escolar.'),
            ('FAMILIAS', 'CLES', 4,
             'Es suficientemente eficaz el procedimiento de resolución de conflictos en el Centro.'),
            ('FAMILIAS', 'PART', 5,
             'Hay un alto porcentaje de familias (más del 50%) que se interesan por participar en el proceso de mejora del centro.'),
            ('FAMILIAS', 'PART', 5,
             'Hay un alto porcentaje de familias (más del 50%) que  participan  regularmente en las distintas actividades del Centro.'),
            ('FAMILIAS', 'PART', 5,
             'Se dan respuestas rápidas a las sugerencias o reclamaciones formuladas por las familias.'),
            ('FAMILIAS', 'PART', 5, 'Se informa adecuadamente sobre los cauces y fórmulas de participación.'),
            ('FAMILIAS', 'PART', 5, 'Las asociaciones de madres y padres promueven la participación de las familias.'),
            ('FAMILIAS', 'PART', 6, 'Estoy satisfecho con la labor del Equipo Directivo del Centro.'),
            ('FAMILIAS', 'PART', 6, 'Estoy satisfecho con la planificación que realiza el Centro.'),
            ('FAMILIAS', 'PART', 6, 'Estoy satisfecho con los recursos que ofrece el Centro y con su aprovechamiento.'),
            ('FAMILIAS', 'PART', 6, 'Estoy satisfecho con la formación adquirida por mi hijo.'),
            ('FAMILIAS', 'PART', 6, 'El clima de convivencia en el Centro es satisfactorio.'),
            ('FAMILIAS', 'PART', 6,
             'Me siento satisfecho con el papel que puedo jugar en la educación  de mi hijo en el Centro.'),
            ('FAMILIAS', 'PART', 6, 'Recomendaría a un amigo que trajera a su hijo a estudiar a este Centro.'),
            ('FAMILIAS', 'PART', 6, 'Estoy satisfecho con la pertenencia de mi hijo a este Centro.'),
            ('FAMILIAS', 'REEN', 7, 'Creo que el entorno tiene una imagen positiva del Centro.'),
            ('FAMILIAS', 'RECL', 8, 'El nivel de éxito escolar del alumnado es satisfactorio.'),
            ('FAMILIAS', 'RECL', 8,
             'El nivel de capacitación del alumnado para proseguir su formación es satisfactorio.'),
            ('FAMILIAS', 'RECL', 8,
             'El nivel de capacitación del alumno para lograr una futura inserción laboral es satisfactorio.')]

dimensiones = [('LIDE', 1, 'LIDERAZGO',
                'Se trata de los comportamientos organizativos que dirigen la vida de los Centros, animando y potenciando las acciones de mejora y reconociendo el trabajo de los distintos profesionales y colectivos de los Centros Escolares. Pueden corresponder a los directivos y a otros miembros de la Comunidad Educativa.'),
               ('PLAN', 2, 'PLANIFICACIÓN',
                'Es el proceso de identificación de las necesidades de mejora y posterior articulación y estructuración de las actuaciones que se deben desarrollar para satisfacerlas.'),
               ('GERE', 3, 'GESTIÓN DE RECURSOS',
                'Se valora la adecuación de los medios de los que dispone el Centro y de aquellos que ofrece el entorno, así como su utilización, cuidado y aprovechamiento.'),
               ('PRED', 4, 'PROCESO EDUCATIVO',
                'Es el proceso clave de los Centros, mide el conjunto de actividades conducentes a la formación integral de los alumnos.'),
               ('CLES', 5, 'CLIMA ESCOLAR',
                'Mediante este criterio se evalúan las relaciones de convivencia y disciplina del Centro.'),
               ('PART', 6, 'PARTICIPACIÓN',
                'Se evalúa la implicación de los miembros de la Comunidad Educativa en la vida y actividades del Centro.'),
               ('RESU', 7, 'RESULTADOS',
                'Mide la satisfacción que los miembros y usuarios integrantes de los sectores tienen con la situación general del Centro, haciendo referencia a la globalidad de los criterios evaluados anteriormente.'),
               ('PERS', '3', 'PERSONAS',
                'Se evalúan los sistemas de gestión del desarrollo e implicación de las personas en el Centro; y los procedimientos de análisis de estos condicionantes.'),
               ('OGPR', '5', 'ORGANIZACIÓN - GESTIÓN DE LOS PROCESOS',
                'Se trata de la evaluación de las diferentes tareas generales de gestión, autoevaluación y revisión de los procesos y actuaciones que se desarrollan en el Centro o Servicio Educativo.'),
               ('REEN', '10', 'RESULTADOS EN EL ENTORNO',
                'Se evalúa la percepción del impacto de las actuaciones del Centro en la sociedad.'),
               ('RECL', '11', 'RESULTADOS CLAVES',
                'Son los resultados finales del funcionamiento del centro, que se derivan de sus procesos clave.')]
