TIPOS = (('P', 'PASAPORTE'), ('I', 'CARTA DE IDENTIDAD EXTRANJERA'), ('N', 'NIE O TARJETA ESPAÑOLA DE EXTRANJEROS'),
         ('P', 'PASAPORTE'), ('I', 'CARTA DE IDENTIDAD EXTRANJERA'), ('N', 'NIE O TARJETA ESPAÑOLA DE EXTRANJEROS'),
         ('X', 'PERMISO DE RESIDENCIA DE ESTADO MIEMBRO DE LA UE'), ('', 'SELECCIONAR...'), ('D', 'DNI'),
         ('P', 'PASAPORTE'), ('C', 'PERMISO CONDUCIR ESPAÑOL'))

TIPO_ESPANA = (('', 'SELECCIONAR...'), ('D', 'DNI'), ('P', 'PASAPORTE'), ('C', 'PERMISO CONDUCIR ESPAÑOL'))

TIPO_UE = (('P', 'PASAPORTE'), ('I', 'CARTA DE IDENTIDAD EXTRANJERA'), ('N', 'NIE O TARJETA ESPAÑOLA DE EXTRANJEROS'),
           ('X', 'PERMISO DE RESIDENCIA DE ESTADO MIEMBRO DE LA UE'))

TIPO_OTRO = (('P', 'PASAPORTE'), ('I', 'CARTA DE IDENTIDAD EXTRANJERA'), ('N', 'NIE O TARJETA ESPAÑOLA DE EXTRANJEROS'))

p = (
    'Alemania', 'Austria', 'Bulgaria', 'Bélgica', 'Chipre', 'Croacia', 'Dinamarca', 'Eslovaquia', 'Eslovenia', 'España',
    'Estonia', '', 'Finlandia', 'Francia', 'Grecia', 'Hungria', 'Irlanda', 'Islandia', 'Italia', 'Letonia',
    'Liechtenstein',
    'Lituania', 'Luxemburgo', '', 'Malta', 'Noruega', 'Paises Bajos', 'Polonia', 'Portugal', 'Reino Unido',
    'República Checa', 'Rumania', 'Suecia')

P = (
    'ALEMANIA', 'AUSTRIA', 'BULGARIA', 'BELGICA', 'CHIPRE', 'CROACIA', 'DINAMARCA', 'ESLOVAQUIA', 'ESLOVENIA', 'ESPAÑA',
    'ESTONIA', 'FINLANDIA', 'FRANCIA', 'GRECIA', 'HUNGRIA', 'IRLANDA', 'ISLANDIA', 'ITALIA', 'LETONIA', 'LIECHTENSTEIN',
    'LITUANIA', 'LUXEMBURGO', 'MALTA', 'NORUEGA', 'PAISES BAJOS', 'POLONIA', 'PORTUGAL', 'REINO UNIDO',
    'REPUBLICA CHECA', 'RUMANIA', 'SUECIA')

PAISES_EU = [('A9103AAAAA', 'ALEMANIA'), ('A9104AAAAA', 'AUSTRIA'), ('A9105AAAAA', 'BELGICA'),
             ('A9134AAAAA', 'BULGARIA'), ('A9107AAAAA', 'CHIPRE'), ('A9140AAAAA', 'CROACIA'),
             ('A9108AAAAA', 'DINAMARCA'), ('A9158AAAAA', 'ESLOVAQUIA'), ('A9141AAAAA', 'ESLOVENIA'),
             ('A9109AAAAA', 'ESPAÑA'), ('A9137AAAAA', 'ESTONIA'), ('A9110AAAAA', 'FINLANDIA'),
             ('A9111AAAAA', 'FRANCIA'), ('A9113AAAAA', 'GRECIA'), ('A9114AAAAA', 'HUNGRIA'), ('A9115AAAAA', 'IRLANDA'),
             ('A9116AAAAA', 'ISLANDIA'), ('A9117AAAAA', 'ITALIA'), ('A9138AAAAA', 'LETONIA'),
             ('A9118AAAAA', 'LIECHTENSTEIN'), ('A9139AAAAA', 'LITUANIA'), ('A9119AAAAA', 'LUXEMBURGO'),
             ('A9120AAAAA', 'MALTA'), ('A9122AAAAA', 'NORUEGA'), ('A9123AAA1A', 'PAISES BAJOS'),
             ('A9124AAAAA', 'POLONIA'), ('A9125AAAAA', 'PORTUGAL'), ('A9112AAA1A', 'REINO UNIDO'),
             ('A9157AAAAA', 'REPUBLICA CHECA'), ('A9127AAAAA', 'RUMANIA'), ('A9128AAAAA', 'SUECIA')]

PAISES_EU_CODES = ['A9103AAAAA', 'A9104AAAAA', 'A9105AAAAA', 'A9134AAAAA', 'A9107AAAAA', 'A9140AAAAA', 'A9108AAAAA',
                   'A9158AAAAA', 'A9141AAAAA', 'A9109AAAAA', 'A9137AAAAA', 'A9110AAAAA', 'A9111AAAAA', 'A9113AAAAA',
                   'A9114AAAAA', 'A9115AAAAA', 'A9116AAAAA', 'A9117AAAAA', 'A9138AAAAA', 'A9118AAAAA', 'A9139AAAAA',
                   'A9119AAAAA', 'A9120AAAAA', 'A9122AAAAA', 'A9123AAA1A', 'A9124AAAAA', 'A9125AAAAA', 'A9112AAA1A',
                   'A9157AAAAA', 'A9127AAAAA', 'A9128AAAAA']
