# Generated by Selenium IDE
# import pytest
import logging
import time
import json
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from vut.models import RegistroPolicia

logger = logging.getLogger('django')

# {v[0]:(i+2, v[1]) for i,v in enumerate(PAISES)}
xpath_indexes_paises = {
    'A9401AAAAA': (2, 'AFGANISTAN'), 'A9399AAAAA': (3, 'AFRICA'), 'A9102AAAAA': (4, 'ALBANIA'),
    'A9103AAAAA': (5, 'ALEMANIA'), 'A9299AAAAA': (6, 'AMERICA'), 'A9133AAAAA': (7, 'ANDORRA'),
    'A9301AAAAA': (8, 'ANGOLA'), 'A9255AAAAA': (9, 'ANTIGUA BARBUDA'), 'A9200AAAAA': (10, 'ANTILLAS NEERLANDESAS'),
    'A9600AAAAA': (11, 'APATRIDA'), 'A9403AAA1A': (12, 'ARABIA SAUDITA'), 'A9304AAAAA': (13, 'ARGELIA'),
    'A9202AAAAA': (14, 'ARGENTINA'), 'A9142AAAAA': (15, 'ARMENIA'), 'A9257AAAAA': (16, 'ARUBA'),
    'A9499AAAAA': (17, 'ASIA'), 'A9500AAAAA': (18, 'AUSTRALIA'), 'A9104AAAAA': (19, 'AUSTRIA'),
    'A9143AAA2A': (20, 'AZERBAYAN'), 'A9203AAAAA': (21, 'BAHAMAS'), 'A9405AAAAA': (22, 'BAHREIN'),
    'A9432AAAAA': (23, 'BANGLADESH'), 'A9205AAAAA': (24, 'BARBADOS'), 'A9105AAAAA': (25, 'BELGICA'),
    'A9207AAAAA': (26, 'BELICE'), 'A9407AAAAA': (27, 'BHUTAN'), 'A9144AAAAA': (28, 'BIELORRUSIA'),
    'A9204AAAAA': (29, 'BOLIVIA'), 'A9156AAAAA': (30, 'BOSNIA HERZEGOVINA'), 'A9305AAAAA': (31, 'BOTSWANA'),
    'A9206AAAAA': (32, 'BRASIL'), 'A9409AAAAA': (33, 'BRUNEI'), 'A9134AAAAA': (34, 'BULGARIA'),
    'A9303AAAAA': (35, 'BURKINA FASO'), 'A9321AAAAA': (36, 'BURUNDI'), 'A9315AAAAA': (37, 'CABO VERDE'),
    'A9402AAAAA': (38, 'CAMBOYA'), 'A9308AAAAA': (39, 'CAMERUN'), 'A9208AAAAA': (40, 'CANADA'),
    'A9372AAAAA': (41, 'CHAD'), 'A9106AAAAD': (42, 'CHECOSLOVAQUIA'), 'A9210AAAAA': (43, 'CHILE'),
    'A9406AAAAA': (44, 'CHINA'), 'A9107AAAAA': (45, 'CHIPRE'), 'A9212AAAAA': (46, 'COLOMBIA'),
    'A9311AAAAA': (47, 'COMORES'), 'A9460AAAAA': (48, 'COREA NORTE'), 'A9410AAAAA': (49, 'COREA SUR'),
    'A9314AAAAA': (50, 'COSTA MARFIL'), 'A9214AAAAA': (51, 'COSTA RICA'), 'A9140AAAAA': (52, 'CROACIA'),
    'A9216AAAAA': (53, 'CUBA'), 'A9258AAAAA': (54, 'CURAÇAO'), 'A9108AAAAA': (55, 'DINAMARCA'),
    'A9317AAAAA': (56, 'DJIBOUTI'), 'A9217AAAAA': (57, 'DOMINICA'), 'A9222AAAAA': (58, 'ECUADOR'),
    'A9300AAAAA': (59, 'EGIPTO'), 'A9429AAAAA': (60, 'EMIRATOS ARABES UNIDOS'), 'A9384AAAAA': (61, 'ERITREA'),
    'A9158AAAAA': (62, 'ESLOVAQUIA'), 'A9141AAAAA': (63, 'ESLOVENIA'), 'A9109AAAAA': (64, 'ESPAÑA'),
    'A9525AAA1A': (65, 'ESTADOS FEDERADOS MICRONESIA'), 'A9224AAA1A': (66, 'ESTADOS UNIDOS AMERICA'),
    'A9137AAAAA': (67, 'ESTONIA'), 'A9318AAAAA': (68, 'ETIOPIA'), 'A9199AAAAA': (69, 'EUROPA'),
    'A9396AAAAA': (70, 'FERNANDO POO'), 'A9550AAAAA': (71, 'FIDJI'), 'A9411AAAAA': (72, 'FILIPINAS'),
    'A9110AAAAA': (73, 'FINLANDIA'), 'A9111AAAAA': (74, 'FRANCIA'), 'A9320AAAAA': (75, 'GABON'),
    'A9323AAAAA': (76, 'GAMBIA'), 'A9145AAAAA': (77, 'GEORGIA'), 'A9322AAAAA': (78, 'GHANA'),
    'A9113AAAAA': (79, 'GRECIA'), 'A9228AAAAA': (80, 'GUATEMALA'), 'A9325AAA3A': (81, 'GUINEA'),
    'A9328AAA1A': (82, 'GUINEA BISSAU'), 'A9324AAAAA': (83, 'GUINEA ECUATORIAL'), 'A9225AAAAA': (84, 'GUYANA'),
    'A9230AAAAA': (85, 'HAITI'), 'A9232AAAAA': (86, 'HONDURAS'), 'A9462AAAAA': (87, 'HONG KONG CHINO'),
    'A9114AAAAA': (88, 'HUNGRIA'), 'A9395AAAAA': (89, 'IFNI'), 'A9412AAAAA': (90, 'INDIA'),
    'A9414AAAAA': (91, 'INDONESIA'), 'A9413AAAAA': (92, 'IRAK'), 'A9415AAAAA': (93, 'IRAN'),
    'A9115AAAAA': (94, 'IRLANDA'), 'A9116AAAAA': (95, 'ISLANDIA'), 'A9518AAAAA': (96, 'ISLAS MARIANAS NORTE'),
    'A9520AAAAA': (97, 'ISLAS MARSHALL'), 'A9551AAA1A': (98, 'ISLAS SALOMON'), 'A9417AAAAA': (99, 'ISRAEL'),
    'A9117AAAAA': (100, 'ITALIA'), 'A9233AAAAA': (101, 'JAMAICA'), 'A9416AAAAA': (102, 'JAPON'),
    'A9419AAAAA': (103, 'JORDANIA'), 'A9465AAAAA': (104, 'KAZAJSTAN'), 'A9336AAAAA': (105, 'KENIA'),
    'A9501AAAAA': (106, 'KIRIBATI'), 'A9421AAAAA': (107, 'KUWAIT'), 'A9418AAAAA': (108, 'LAOS'),
    'A9337AAAAA': (109, 'LESOTHO'), 'A9138AAAAA': (110, 'LETONIA'), 'A9423AAAAA': (111, 'LIBANO'),
    'A9342AAAAA': (112, 'LIBERIA'), 'A9344AAAAA': (113, 'LIBIA'), 'A9118AAAAA': (114, 'LIECHTENSTEIN'),
    'A9139AAAAA': (115, 'LITUANIA'), 'A9119AAAAA': (116, 'LUXEMBURGO'), 'A9463AAAAA': (117, 'MACAO'),
    'A9159AAAAA': (118, 'MACEDONIA'), 'A9354AAAAA': (119, 'MADAGASCAR'), 'A9425AAAAA': (120, 'MALASIA'),
    'A9346AAAAA': (121, 'MALAWI'), 'A9436AAAAA': (122, 'MALDIVAS'), 'A9347AAAAA': (123, 'MALI'),
    'A9120AAAAA': (124, 'MALTA'), 'A9348AAAAA': (125, 'MARRUECOS'), 'A9349AAAAA': (126, 'MAURICIO'),
    'A9350AAAAA': (127, 'MAURITANIA'), 'A9234AAA1A': (128, 'MEXICO'), 'A9148AAAAA': (129, 'MOLDAVIA'),
    'A9121AAAAA': (130, 'MONACO'), 'A9427AAAAA': (131, 'MONGOLIA'), 'A9160AAAAA': (132, 'MONTENEGRO'),
    'A9351AAAAA': (133, 'MOZAMBIQUE'), 'A9400AAAAA': (134, 'MYANMAR'), 'A9353AAAAA': (135, 'NAMIBIA'),
    'A9541AAAAA': (136, 'NAURU'), 'A9420AAAAA': (137, 'NEPAL'), 'A9236AAAAA': (138, 'NICARAGUA'),
    'A9360AAAAA': (139, 'NIGER'), 'A9352AAAAA': (140, 'NIGERIA'), 'A9122AAAAA': (141, 'NORUEGA'),
    'A9540AAAAA': (142, 'NUEVA ZELANDA'), 'A9599AAAAA': (143, 'OCEANIA'), 'A9444AAAAA': (144, 'OMAN'),
    'A9123AAA1A': (145, 'PAISES BAJOS'), 'A9424AAA1A': (146, 'PAKISTAN'), 'A9440AAAAA': (147, 'PALESTINA'),
    'A9238AAAAA': (148, 'PANAMA'), 'A9542AAAAA': (149, 'PAPUA NUEVA GUINEA'), 'A9240AAAAA': (150, 'PARAGUAY'),
    'A9242AAAAA': (151, 'PERU'), 'A9124AAAAA': (152, 'POLONIA'), 'A9125AAAAA': (153, 'PORTUGAL'),
    'A9244AAAAA': (154, 'PUERTO RICO'), 'A9431AAAAA': (155, 'QATAR'), 'A9112AAA1A': (156, 'REINO UNIDO'),
    'A9302AAA1A': (157, 'REPUBLICA BENIN'), 'A9310AAA1A': (158, 'REPUBLICA CENTROAFRICANA'),
    'A9157AAAAA': (159, 'REPUBLICA CHECA'), 'A9312AAA1A': (160, 'REPUBLICA CONGO'),
    'A9380AAAAA': (161, 'REPUBLICA DEMOCRATICA CONGO'), 'A9218AAA1A': (162, 'REPUBLICA DOMINICANA'),
    'A9229AAAAA': (163, 'REPUBLICA GRANADA'), 'A9466AAA1A': (164, 'REPUBLICA KIRGUISTAN'),
    'A9369AAAAA': (165, 'REPUBLICA SUDAN SUR'), 'A9397AAAAA': (166, 'RIO MUNI'), 'A9306AAAAA': (167, 'RUANDA'),
    'A9127AAAAA': (168, 'RUMANIA'), 'A9149AAAAA': (169, 'RUSIA'), 'A9398AAAAA': (170, 'SAHARA'),
    'A9256AAA1A': (171, 'SAINT KITTS NEVIS'), 'A9220AAAAA': (172, 'SALVADOR'), 'A9552AAAAA': (173, 'SAMOA OCCIDENTAL'),
    'A9135AAAAA': (174, 'SAN MARINO'), 'A9259AAAAA': (175, 'SAN MARTIN'), 'A9254AAA1A': (176, 'SAN VICENTE GRANADINAS'),
    'A9253AAAAA': (177, 'SANTA LUCIA'), 'A9136AAA2A': (178, 'SANTA SEDE'), 'A9361AAAAA': (179, 'SANTO TOME PRINCIPE'),
    'A9362AAAAA': (180, 'SENEGAL'), 'A9155AAAAA': (181, 'SERBIA'), 'A9363AAAAA': (182, 'SEYCHELLES'),
    'A9364AAAAA': (183, 'SIERRA LEONA'), 'A9426AAAAA': (184, 'SINGAPUR'), 'A9433AAAAA': (185, 'SIRIA'),
    'A9365AAAAA': (186, 'SOMALIA'), 'A9404AAAAA': (187, 'SRI LANKA'), 'A9367AAAAA': (188, 'SUDAFRICA'),
    'A9368AAAAA': (189, 'SUDAN'), 'A9128AAAAA': (190, 'SUECIA'), 'A9129AAAAA': (191, 'SUIZA'),
    'A9250AAAAA': (192, 'SURINAM'), 'A9371AAAAA': (193, 'SWAZILANDIA'), 'A9469AAAAA': (194, 'TADJIKISTAN'),
    'A9408AAA3A': (195, 'TAIWAN TAIPEI'), 'A9370AAAAA': (196, 'TANZANIA'), 'A9428AAAAA': (197, 'THAILANDIA'),
    'A9464AAAAA': (198, 'TIMOR ORIENTAL'), 'A9374AAAAA': (199, 'TOGO'), 'A9554AAAAA': (200, 'TONGA'),
    'A9245AAAAA': (201, 'TRINIDAD TOBAGO'), 'A9378AAAAA': (202, 'TUNEZ'), 'A9467AAAAA': (203, 'TURKMENIA'),
    'A9130AAAAA': (204, 'TURQUIA'), 'A9560AAAAA': (205, 'TUVALU'), 'A9152AAAAA': (206, 'UCRANIA'),
    'A9358AAAAA': (207, 'UGANDA'), 'A9190AAA1A': (208, 'UNION EUROPEA'), 'A9246AAAAA': (209, 'URUGUAY'),
    'A9468AAAAA': (210, 'UZBEKISTAN'), 'A9565AAAAA': (211, 'VANUATU'), 'A9248AAAAA': (212, 'VENEZUELA'),
    'A9430AAAAA': (213, 'VIETNAM'), 'A9434AAAAA': (214, 'YEMEN'), 'A9132AAAAD': (215, 'YUGOSLAVIA'),
    'A9382AAAAA': (216, 'ZAMBIA'), 'A9357AAAAA': (217, 'ZIMBABWE')}


def RegistraViajeroPN(viajero):
    options = Options()
    options.headless = True
    # driver = webdriver.Firefox(options=options, executable_path=r'C:\Utility\BrowserDrivers\geckodriver.exe')
    driver = webdriver.Firefox(options=options)
    try:
        driver.get("https://webpol.policia.es/e-hotel/login")
        logger.info("driver login")
        driver.set_window_size(1920, 1080)
        driver.find_element(By.ID, "password").send_keys(viajero.reserva.vivienda.police_pass)
        logger.info("send police_pass")
        driver.find_element(By.ID, "username").send_keys(viajero.reserva.vivienda.police_code)
        logger.info("send police_code")
        driver.find_element(By.CSS_SELECTOR, ".fa-sign-in").click()
        logger.info("click sign-in")
        driver.find_element(By.ID, "grabadorManual").click()
        logger.info("click grabadorManual")
        driver.find_element(By.ID, "nombre").send_keys(viajero.nombre)
        driver.find_element(By.ID, "apellido1").send_keys(viajero.apellido1)
        driver.find_element(By.ID, "apellido2").send_keys(viajero.apellido2)
        logger.info("send nombre y apellidos")
        driver.find_element_by_xpath('//*[@id="nacionalidad_chosen"]').click()
        # Ejemplos: 58 ecuador, 64 españa, ...
        ind = xpath_indexes_paises[viajero.pais][0]
        xph = '/html/body/div[4]/div/div/form/div/fieldset/div[2]/div/fieldset/div[2]/div[1]/div/div/div/ul/li[%s]' % ind
        driver.find_element_by_xpath(xph).click()
        driver.find_element_by_xpath('//*[@id="tipoDocumento_chosen"]').click()
        # driver.find_element_by_xpath('/html/body/div[4]/div/div/form/div/fieldset/div[2]/div/fieldset/div[2]/div[2]/div/div/a').click()
        time.sleep(1)
        # La selección del tipo de documento (indice de xpath) depende de la nacionalidad elegida:
        # España:
        # DNI:       /html/body/div[4]/div/div/form/div/fieldset/div[2]/div/fieldset/div[2]/div[2]/div/div/div/ul/li[2]
        # Pasaporte: /html/body/div[4]/div/div/form/div/fieldset/div[2]/div/fieldset/div[2]/div[2]/div/div/div/ul/li[3]
        # C. Conduc: /html/body/div[4]/div/div/form/div/fieldset/div[2]/div/fieldset/div[2]/div[2]/div/div/div/ul/li[4]
        # Europa:
        # Pasaporte: /html/body/div[4]/div/div/form/div/fieldset/div[2]/div/fieldset/div[2]/div[2]/div/div/div/ul/li[2]
        # Carta ext: /html/body/div[4]/div/div/form/div/fieldset/div[2]/div/fieldset/div[2]/div[2]/div/div/div/ul/li[3]
        # NIE:       /html/body/div[4]/div/div/form/div/fieldset/div[2]/div/fieldset/div[2]/div[2]/div/div/div/ul/li[4]
        # Perm. UE:  /html/body/div[4]/div/div/form/div/fieldset/div[2]/div/fieldset/div[2]/div[2]/div/div/div/ul/li[5]
        # Mundo:
        # Pasaporte: /html/body/div[4]/div/div/form/div/fieldset/div[2]/div/fieldset/div[2]/div[2]/div/div/div/ul/li[2]
        # Carta ext: /html/body/div[4]/div/div/form/div/fieldset/div[2]/div/fieldset/div[2]/div[2]/div/div/div/ul/li[3]
        # NIE:       /html/body/div[4]/div/div/form/div/fieldset/div[2]/div/fieldset/div[2]/div[2]/div/div/div/ul/li[4]
        if viajero.pais == 'A9109AAAAA':
            xpath_indexes_documentos = {'D': 2, 'P': 3, 'C': 4}
        else:
            xpath_indexes_documentos = {'P': 2, 'I': 3, 'N': 4, 'X': 5}
        idoc = xpath_indexes_documentos[viajero.tipo_ndi]
        xph = '/html/body/div[4]/div/div/form/div/fieldset/div[2]/div/fieldset/div[2]/div[2]/div/div/div/ul/li[%s]' % idoc
        driver.find_element_by_xpath(xph).click()
        # time.sleep(1)
        driver.find_element(By.ID, "numIdentificacion").send_keys(viajero.ndi)
        driver.find_element(By.ID, "fechaExpedicionDoc").send_keys(viajero.fecha_exp.strftime('%d/%m/%Y'))
        driver.find_element(By.ID, "dia").send_keys(viajero.nacimiento.day)
        driver.find_element(By.ID, "mes").send_keys(viajero.nacimiento.month)
        driver.find_element(By.ID, "ano").send_keys(viajero.nacimiento.year)
        logger.info("send nacimiento")
        # driver.find_element(By.CSS_SELECTOR, "#sexo_chosen span").click()
        xph = '/html/body/div[4]/div/div/form/div/fieldset/div[2]/div/fieldset/div[3]/div[2]/div/div/a/span'
        driver.find_element_by_xpath(xph).click()
        time.sleep(1)
        # Sexo: 2 -> Masculino, 3-> Femenino
        isexo = '2' if viajero.sexo == 'M' else '3'
        xph = '/html/body/div[4]/div/div/form/div/fieldset/div[2]/div/fieldset/div[3]/div[2]/div/div/div/ul/li[%s]' % isexo
        driver.find_element_by_xpath(xph).click()
        driver.find_element(By.ID, "fechaEntrada").send_keys(viajero.fecha_entrada.strftime('%d/%m/%Y'))
        # Botón de grabar:
        driver.find_element_by_xpath('/html/body/div[4]/div/div/form/div/fieldset/div[3]/button[1]/span').click()
        logger.info("click grabar")
        time.sleep(1)
        # Cancelar impresión del parte:
        driver.find_element_by_xpath('/html/body/div[1]/div/div/div[2]/form/div[2]/button[2]/span').click()
        time.sleep(0.5)
        # salir: /html/body/div[2]/form/div/div[2]/i[2]
        driver.find_element_by_xpath('/html/body/div[2]/form/div/div[2]/i[2]').click()
        time.sleep(0.5)
        driver.quit()
    except:
        driver.quit()
