# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# Código de centro asociado a un contenedor desechable. Para los casos en los que no se pueda borrar la entidad:
CODE_CONTENEDOR = '1010101010'
# gauser asociado al centro contenedor al que se podrán asignar Gauser_extras en caso de no poder borrarse:
GAUSER_COMODIN = 'qazwsxedcrfvtgbyhnujmikolp'

WEEKDAYS = {}
RONDAS = (
    ('0', '2010/2011'),
    ('1', '2011/2012'),
    ('2', '2012/2013'),
    ('3', '2013/2014'),
    ('4', '2014/2015'),
)

PROVINCIAS = (
    ('0', 'Elige provincia'),
    ('01', 'Álava/Araba'),
    ('02', 'Albacete'),
    ('03', 'Alicante/Alacant'),
    ('04', 'Almería'),
    ('33', 'Asturias'),
    ('05', 'Ávila'),
    ('06', 'Badajoz'),
    ('08', 'Barcelona'),
    ('09', 'Burgos'),
    ('10', 'Cáceres'),
    ('11', 'Cádiz'),
    ('39', 'Cantabria'),
    ('12', 'Castellón/Castelló'),
    ('51', 'Ceuta'),
    ('13', 'Ciudad Real'),
    ('14', 'Córdoba'),
    ('16', 'Cuenca'),
    ('17', 'Gerona/Girona'),
    ('35', 'Las Palmas'),
    ('18', 'Granada'),
    ('19', 'Guadalajara'),
    ('20', 'Guipúzcoa/Guipuzkoa'),
    ('21', 'Huelva'),
    ('22', 'Huesca'),
    ('07', 'Islas Baleares/Illes Balears'),
    ('23', 'Jaén'),
    ('15', 'A Coruña'),
    ('26', 'La Rioja'),
    ('24', 'León'),
    ('25', 'Lérida/Lleida'),
    ('27', 'Lugo'),
    ('28', 'Madrid'),
    ('29', 'Málaga'),
    ('52', 'Melilla'),
    ('30', 'Murcia'),
    ('31', 'Navarra'),
    ('32', 'Orense/Ourense'),
    ('34', 'Palencia'),
    ('36', 'Pontevedra'),
    ('37', 'Salamanca'),
    ('40', 'Segovia'),
    ('41', 'Sevilla'),
    ('42', 'Soria'),
    ('43', 'Tarragona'),
    ('38', 'Santa Cruz de Tenerife'),
    ('44', 'Teruel'),
    ('45', 'Toledo'),
    ('46', 'Valencia/Valéncia'),
    ('47', 'Valladolid'),
    ('48', 'Vizcaya/Bizkaia'),
    ('49', 'Zamora'),
    ('50', 'Zaragoza'))

SEXO = (
    ('H', 'Hombre'),
    ('M', 'Mujer'),
)

DIAS = (
    ('L', 'Lunes'),
    ('M', 'Martes'),
    ('X', 'Miércoles'),
    ('J', 'Jueves'),
    ('V', 'Viernes'),
    ('S', 'Sábado'),
    ('D', 'Domingo'),
)
MESES = ('Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre',
         'Octubre', 'Noviembre', 'Diciembre')

LOCALIDADES = (
    ('26339', 'ABALOS'),
    ('26160', 'AGONCILLO'),
    ('26530', 'AGUILAR DEL RIO ALHAMA'),
    ('26120', 'ALBELDA DE IREGUA'),
    ('26141', 'ALBERITE'),
    ('26509', 'ALCANADRE'),
    ('26559', 'ALDEANUEVA DE EBRO'),
    ('26324', 'ALESANCO'),
    ('26540', 'ALFARO'),
    ('26322', 'ANGUIANO'),
    ('26589', 'ARNEDILLO'),
    ('26580', 'ARNEDO'),
    ('26151', 'ARRUBAL'),
    ('26513', 'AUSEJO'),
    ('26560', 'AUTOL'),
    ('26257', 'BAÑARES'),
    ('26320', 'BAÑOS DE RIO TOBIA'),
    ('26327', 'BERCEO'),
    ('26588', 'BERGASA'),
    ('26321', 'BOBADILLA'),
    ('26290', 'BRIÑAS'),
    ('26330', 'BRIONES'),
    ('26325', 'CAÑAS'),
    ('26529', 'CABRETON'),
    ('26500', 'CALAHORRA'),
    ('26230', 'CASALARREINA'),
    ('26240', 'CASTAÑARES DE RIOJA'),
    ('26350', 'CENICERO'),
    ('26520', 'CERVERA DEL RIO ALHAMA'),
    ('26210', 'CIHURI'),
    ('26258', 'CIRUEÑA'),
    ('26311', 'CORDOVIN'),
    ('26526', 'CORNAGO'),
    ('26214', 'CUZCURRITA DE RIO TIRON'),
    ('26375', 'ENTRENA'),
    ('26280', 'EZCARAY'),
    ('26211', 'FONZALECHE'),
    ('26360', 'FUENMAYOR'),
    ('26144', 'GALILEA'),
    ('26259', 'GRAÑON'),
    ('26200', 'HARO'),
    ('26584', 'HERCE'),
    ('26323', 'HORMILLA'),
    ('26372', 'HORNOS DE MONCALVILLO'),
    ('26314', 'HUERCANOS'),
    ('26525', 'IGEA'),
    ('26134', 'JALON DE CAMEROS'),
    ('26131', 'LAGUNILLA DE JUBERA'),
    ('26140', 'LARDERO'),
    ('26001', 'LOGROÑO-26001'),
    ('26002', 'LOGROÑO-26002'),
    ('26003', 'LOGROÑO-26003'),
    ('26004', 'LOGROÑO-26004'),
    ('26005', 'LOGROÑO-26005'),
    ('26006', 'LOGROÑO-26006'),
    ('26007', 'LOGROÑO-26007'),
    ('26008', 'LOGROÑO-26008'),
    ('26009', 'LOGROÑO-26009'),
    ('26132', 'LUEZAS'),
    ('26315', 'MANJARRES'),
    ('26374', 'MEDRANO'),
    ('26143', 'MURILLO DE RIO LEZA'),
    ('26587', 'MURO DE AGUAS'),
    ('26300', 'NAJERA'),
    ('26190', 'NALDA'),
    ('26533', 'NAVAJUN'),
    ('26586', 'NAVALSAZ'),
    ('26370', 'NAVARRETE'),
    ('26124', 'NIEVA DE CAMEROS'),
    ('26213', 'OCHANDURI'),
    ('26148', 'OCON'),
    ('26220', 'OLLAURI'),
    ('26510', 'PRADEJON'),
    ('26570', 'QUEL'),
    ('26100', 'RIBABELLOSA'),
    ('26130', 'RIBAFRECHA'),
    ('26550', 'RINCON DE SOTO'),
    ('26222', 'RODEZNO'),
    ('26212', 'SAJAZARRA'),
    ('26340', 'SAN ASENSIO'),
    ('26326', 'SAN MILLAN DE LA COGOLLA'),
    ('26216', 'SAN MILLAN DE YECORA'),
    ('26133', 'SAN ROMAN DE CAMEROS'),
    ('26338', 'SAN VICENTE DE LA SONSIERRA'),
    ('26250', 'SANTO DOMINGO DE LA CALZADA'),
    ('26260', 'SANTURDE'),
    ('26376', 'SOJUELA'),
    ('26191', 'SORZANO'),
    ('26371', 'SOTES'),
    ('26224', 'TORRECILLA SOBRE ALESANCO'),
    ('26215', 'TREVIANA'),
    ('26312', 'TRICIO'),
    ('26512', 'TUDELILLA'),
    ('26313', 'URUÑUELA'),
    ('26532', 'VALDEMADERA'),
    ('26528', 'VALVERDE'),
    ('26527', 'VENTAS DEL BAÑO'),
    ('26121', 'VIGUERA'),
    ('26292', 'VILLALBA DE RIOJA'),
    ('26256', 'VILLALOBAR DE RIOJA'),
    ('26142', 'VILLAMEDIANA DE IREGUA'),
    ('26123', 'VILLANUEVA DE CAMEROS'),
    ('26511', 'VILLAR DE ARNEDO, EL'),
    ('26329', 'VILLAVELAYO'),
    ('26125', 'VILLOSLADA DE CAMEROS'),
    ('26291', 'ZARRATON'),
    ('26288', 'ZORRAQUIN'))

PAISES = (
    ("100", "Afghanistan"),
    ("101", "Albania"),
    ("102", "Algeria"),
    ("103", "American Samoa"),
    ("104", "Andorra"),
    ("105", "Angola"),
    ("106", "Anguilla"),
    ("107", "Antigua & Barbuda"),
    ("108", "Argentina"),
    ("109", "Armenia"),
    ("110", "Aruba"),
    ("111", "Australia"),
    ("112", "Austria"),
    ("113", "Azerbaijan"),
    ("114", "Bahamas, The"),
    ("115", "Bahrain"),
    ("116", "Bangladesh"),
    ("117", "Barbados"),
    ("118", "Belarus"),
    ("119", "Belgium"),
    ("120", "Belize"),
    ("121", "Benin"),
    ("122", "Bermuda"),
    ("123", "Bhutan"),
    ("124", "Bolivia"),
    ("125", "Bosnia & Herzegovina"),
    ("126", "Botswana"),
    ("127", "Brazil"),
    ("128", "British Virgin Is."),
    ("129", "Brunei"),
    ("130", "Bulgaria"),
    ("131", "Burkina Faso"),
    ("132", "Burma"),
    ("133", "Burundi"),
    ("134", "Cambodia"),
    ("135", "Cameroon"),
    ("136", "Canada"),
    ("137", "Cape Verde"),
    ("138", "Cayman Islands"),
    ("139", "Central African Rep."),
    ("140", "Chad"),
    ("141", "Chile"),
    ("142", "China"),
    ("143", "Colombia"),
    ("144", "Comoros"),
    ("145", "Congo, Dem. Rep."),
    ("146", "Congo, Repub. of the"),
    ("147", "Cook Islands"),
    ("148", "Costa Rica"),
    ("149", "Cote d'Ivoire"),
    ("150", "Croatia"),
    ("151", "Cuba"),
    ("152", "Cyprus"),
    ("153", "Czech Republic"),
    ("154", "Denmark"),
    ("155", "Djibouti"),
    ("156", "Dominica"),
    ("157", "Dominican Republic"),
    ("158", "East Timor"),
    ("159", "Ecuador"),
    ("160", "Egypt"),
    ("161", "El Salvador"),
    ("162", "Equatorial Guinea"),
    ("163", "Eritrea"),
    ("164", "Estonia"),
    ("165", "Ethiopia"),
    ("166", "Faroe Islands"),
    ("167", "Fiji"),
    ("168", "Finland"),
    ("169", "France"),
    ("170", "French Guiana"),
    ("171", "French Polynesia"),
    ("172", "Gabon"),
    ("173", "Gambia, The"),
    ("174", "Gaza Strip"),
    ("175", "Georgia"),
    ("176", "Germany"),
    ("177", "Ghana"),
    ("178", "Gibraltar"),
    ("179", "Greece"),
    ("180", "Greenland"),
    ("181", "Grenada"),
    ("182", "Guadeloupe"),
    ("183", "Guam"),
    ("184", "Guatemala"),
    ("185", "Guernsey"),
    ("186", "Guinea"),
    ("187", "Guinea-Bissau"),
    ("188", "Guyana"),
    ("189", "Haiti"),
    ("190", "Honduras"),
    ("191", "Hong Kong"),
    ("192", "Hungary"),
    ("193", "Iceland"),
    ("194", "India"),
    ("195", "Indonesia"),
    ("196", "Iran"),
    ("197", "Iraq"),
    ("198", "Ireland"),
    ("199", "Isle of Man"),
    ("200", "Israel"),
    ("201", "Italy"),
    ("202", "Jamaica"),
    ("203", "Japan"),
    ("204", "Jersey"),
    ("205", "Jordan"),
    ("206", "Kazakhstan"),
    ("207", "Kenya"),
    ("208", "Kiribati"),
    ("209", "Korea, North"),
    ("210", "Korea, South"),
    ("211", "Kuwait"),
    ("212", "Kyrgyzstan"),
    ("213", "Laos"),
    ("214", "Latvia"),
    ("215", "Lebanon"),
    ("216", "Lesotho"),
    ("217", "Liberia"),
    ("218", "Libya"),
    ("219", "Liechtenstein"),
    ("220", "Lithuania"),
    ("221", "Luxembourg"),
    ("222", "Macau"),
    ("223", "Macedonia"),
    ("224", "Madagascar"),
    ("225", "Malawi"),
    ("226", "Malaysia"),
    ("227", "Maldives"),
    ("228", "Mali"),
    ("229", "Malta"),
    ("230", "Marshall Islands"),
    ("231", "Martinique"),
    ("232", "Mauritania"),
    ("233", "Mauritius"),
    ("234", "Mayotte"),
    ("235", "Mexico"),
    ("236", "Micronesia, Fed. St."),
    ("237", "Moldova"),
    ("238", "Monaco"),
    ("239", "Mongolia"),
    ("240", "Montserrat"),
    ("241", "Morocco"),
    ("242", "Mozambique"),
    ("243", "Namibia"),
    ("244", "Nauru"),
    ("245", "Nepal"),
    ("246", "Netherlands"),
    ("247", "Netherlands Antilles"),
    ("248", "New Caledonia"),
    ("249", "New Zealand"),
    ("250", "Nicaragua"),
    ("251", "Niger"),
    ("252", "Nigeria"),
    ("253", "N. Mariana Islands"),
    ("254", "Norway"),
    ("255", "Oman"),
    ("256", "Pakistan"),
    ("257", "Palau"),
    ("258", "Panama"),
    ("259", "Papua New Guinea"),
    ("260", "Paraguay"),
    ("261", "Peru"),
    ("262", "Philippines"),
    ("263", "Poland"),
    ("264", "Portugal"),
    ("265", "Puerto Rico"),
    ("266", "Qatar"),
    ("267", "Reunion"),
    ("268", "Romania"),
    ("269", "Russia"),
    ("270", "Rwanda"),
    ("271", "Saint Helena"),
    ("272", "Saint Kitts & Nevis"),
    ("273", "Saint Lucia"),
    ("274", "St Pierre & Miquelon"),
    ("275", "Saint Vincent and the Grenadines"),
    ("276", "Samoa"),
    ("277", "San Marino"),
    ("278", "Sao Tome & Principe"),
    ("279", "Saudi Arabia"),
    ("280", "Senegal"),
    ("281", "Serbia"),
    ("282", "Seychelles"),
    ("283", "Sierra Leone"),
    ("284", "Singapore"),
    ("285", "Slovakia"),
    ("286", "Slovenia"),
    ("287", "Solomon Islands"),
    ("288", "Somalia"),
    ("289", "South Africa"),
    ("290", "España"),
    ("291", "Sri Lanka"),
    ("292", "Sudan"),
    ("293", "Suriname"),
    ("294", "Swaziland"),
    ("295", "Sweden"),
    ("296", "Switzerland"),
    ("297", "Syria"),
    ("298", "Taiwan"),
    ("299", "Tajikistan"),
    ("300", "Tanzania"),
    ("301", "Thailand"),
    ("302", "Togo"),
    ("303", "Tonga"),
    ("304", "Trinidad & Tobago"),
    ("305", "Tunisia"),
    ("306", "Turkey"),
    ("307", "Turkmenistan"),
    ("308", "Turks & Caicos Is"),
    ("309", "Tuvalu"),
    ("310", "Uganda"),
    ("311", "Ukraine"),
    ("312", "United Arab Emirates"),
    ("313", "United Kingdom"),
    ("314", "United States"),
    ("315", "Uruguay"),
    ("316", "Uzbekistan"),
    ("317", "Vanuatu"),
    ("318", "Venezuela"),
    ("319", "Vietnam"),
    ("320", "Virgin Islands"),
    ("321", "Wallis and Futuna"),
    ("322", "West Bank"),
    ("323", "Western Sahara"),
    ("324", "Yemen"),
    ("325", "Zambia"),
    ("326", "Zimbabwe"))

########################################################################################################
CARGOS = [{'clave_cargo': 'g_inspector_educacion', 'cargo': 'Inspector de Educación',
           'permisos': ['acceso_datos_entidad', 'acceso_calendario', 'acceso_vista_calendario', 'crea_eventos',
                        'acceso_gestion_documental', 'acceso_documentos', 'crea_carpetas', 'sube_archivos',
                        'acceso_cuestionarios', 'acceso_formularios', 'crea_formularios', 'copia_formularios',
                        'acceso_cupos', 'acceso_acciones_usuarios1', 'acceso_registro', 'acceso_reparaciones',
                        'crea_solicitud_reparacion', 'acceso_reuniones', 'acceso_conv_template', 'c_conv_template',
                        'acceso_faqs', 'acceso_inspeccion_educativa', 'es_inspector_educacion', 'acceso_tareas_ie',
                        'crea_tareas_ie', 'edita_tareas_ie', 'copia_tareas_ie', 'borra_tareas_ie',
                        'acceso_conv_reunion', 'c_conv_reunion', 'acceso_informes_ie', 'crea_informes_ie',
                        'acceso_plantilla_organica', 'acceso_mis_formularios', 'acceso_formularios_disponibles',
                        'acceso_gestion_entidad', 'acceso_redactar_actas_reunion', 'w_sus_actas_reunion',
                        'acceso_faqs_entidad', 'acceso_plantillas_informes_ie', 'acceso_asignar_centros_inspeccion',
                        'acceso_control_asistencia_reunion', 'acceso_firmar_actas_reunion', 'acceso_faqs_sugeridas',
                        'r_actas_reunion', 'acceso_lectura_actas_reunion', 'acceso_programaciones_didacticas',
                        'acceso_progsecundaria', 'acceso_cuaderno_docente', 'acceso_repositorio_sap',
                        've_todas_programaciones', 'crea_programaciones']},
          {'clave_cargo': 'g_docente', 'cargo': 'Docente',
           'permisos': ['acceso_calendario', 'acceso_vista_calendario', 'crea_eventos', 'acceso_gestion_documental',
                        'acceso_documentos', 'acceso_cuestionarios', 'acceso_formularios', 'crea_formularios',
                        'acceso_horarios', 'acceso_acciones_usuarios1', 'acceso_convivencia', 'acceso_absentismo',
                        'crea_actuacion_absentismo', 'acceso_reparaciones', 'crea_solicitud_reparacion',
                        'acceso_actividades', 'crea_actividad', 'acceso_informes_usuarios',
                        'acceso_informes_seguimiento', 'solicita_informes_seguimiento', 'acceso_competencias_clave',
                        'acceso_programaciones_didacticas', 'acceso_evaluar_materias', 'evalua_materias_asignadas',
                        'acceso_reuniones', 'acceso_faqs', 'acceso_sancionar_conductas', 'sancionar_nivel_docente',
                        'genera_informe_sancionador', 'cc_valorar_mis_alumnos', 'acceso_cargar_programaciones',
                        'carga_programaciones', 'descarga_programaciones', 'acceso_mis_formularios',
                        'acceso_formularios_disponibles', 'acceso_informes_tareas', 'solicita_informes_tareas',
                        'acceso_faqs_entidad', 'acceso_horario_usuarios', 've_horarios_usuarios',
                        'acceso_control_asistencia_reunion', 'acceso_firmar_actas_reunion', 'acceso_faqs_sugeridas',
                        'acceso_horario_aulas', 'acceso_lectura_actas_reunion', 'acceso_horarios_subentidades',
                        've_horarios_entidad', 'acceso_guardias_horarios', 'acceso_lectura_actas_reunion',
                        'acceso_progsecundaria', 'acceso_cuaderno_docente', 'acceso_repositorio_sap',
                        'crea_programaciones']},
          {'clave_cargo': 'g_nodocente', 'cargo': 'No docente',
           'permisos': ['acceso_calendario', 'acceso_vista_calendario', 'crea_eventos', 'acceso_gestion_documental',
                        'acceso_documentos', 'acceso_cuestionarios', 'acceso_formularios', 'crea_formularios',
                        'acceso_horarios', 'acceso_acciones_usuarios1', 'acceso_reparaciones', 'crea_solicitud_reparacion',
                        'acceso_faqs', 'acceso_faqs_entidad', 'acceso_horario_usuarios', 've_horarios_usuarios',
                        'acceso_faqs_sugeridas', 'acceso_horario_aulas', 'acceso_horarios_subentidades',
                        've_horarios_entidad', 'acceso_guardias_horarios']},
          {'clave_cargo': 'g_director_general_educacion', 'cargo': 'Director General de Educación',
           'permisos': ['acceso_configuracion', 'acceso_perfiles_permisos', 'asigna_perfiles', 'asigna_permisos',
                        'modifica_texto_menu', 'modifica_pos_menu', 'acceso_datos_entidad', 'acceso_calendario',
                        'acceso_vista_calendario', 'crea_eventos', 've_todos_eventos', 'acceso_gestion_documental',
                        'acceso_documentos', 'crea_carpetas', 'sube_archivos', 've_todas_carpetas',
                        'edita_todos_archivos', 'borra_cualquier_archivo', 'borra_cualquier_carpeta', 'edita_carpetas',
                        'acceso_cuestionarios', 'acceso_formularios', 'crea_formularios', 'copia_formularios',
                        'borra_formularios', 'acceso_cupos', 'acceso_registro', 'crea_registros', 'acceso_reuniones',
                        'acceso_conv_template', 'c_conv_template', 'w_conv_template', 'd_conv_template', 'acceso_faqs',
                        'acceso_configura_faqs', 'crea_secciones_faqs', 'crea_faqs_entidad', 'edita_faqs_entidad',
                        'publica_faqs_entidad', 'acceso_inspeccion_educativa', 'acceso_tareas_ie',
                        'acceso_gestionar_perfiles', 'crea_perfiles', 'borra_perfiles', 'edita_perfiles',
                        'acceso_conv_reunion', 'r_conv_reunion', 'c_conv_reunion', 'w_conv_reunion', 'd_conv_reunion',
                        'm_conv_reunion', 'acceso_informes_ie', 'crea_informes_ie', 'acceso_plantilla_organica',
                        'acceso_mis_formularios', 'acceso_formularios_disponibles', 'acceso_gestion_entidad',
                        'acceso_redactar_actas_reunion', 'w_sus_actas_reunion', 'w_actas_subentidades_reunion',
                        'w_cualquier_acta_reunion', 'mail_actas_reunion', 'acceso_faqs_entidad',
                        'acceso_plantillas_informes_ie', 'acceso_gestionar_subentidades', 'crea_subentidades',
                        'borra_subentidades', 'edita_subentidades', 'acceso_miembros_entidad', 'listado_usuarios',
                        'acceso_control_asistencia_reunion', 'acceso_firmar_actas_reunion', 'acceso_faqs_sugeridas',
                        'acepta_faqs_sugeridas', 'acceso_listados_usuarios', 'r_actas_reunion',
                        'acceso_lectura_actas_reunion', 'acceso_doc_configuration']}
          ]
