# -*- coding: utf-8 -*-

CUE = [
    {'dim': 'DEDICACIÓN AL CENTRO',
     'subdims': [
         {
             'subdim': 'Participación en los órganos colegiados y de coordinación del docente, así como en iniciativas para mejorar la práctica docente y el trabajo en equipo.',
             'valor': 2,
             'pregs': [
                 {'subsub': 'Participación en los órganos de gobierno',
                  'preg': 'Se interesa por lo tratado en el consejo escolar, pidiendo información y haciendo propuestas a sus representantes y al equipo directivo.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': True,
                  'tutor': False,
                  'inspector': False
                  },
                 {'subsub': 'Participación en los órganos de gobierno',
                  'preg': 'Participa activamente en el claustro, haciendo propuestas viables sobre los temas que figuran en el orden del día y propone, para su discusión, iniciativas de interés general.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': True,
                  'tutor': False,
                  'inspector': False
                  },
                 {'subsub': 'Participación en los órganos de gobierno',
                  'preg': 'Asume responsabilidades como miembro del claustro participando en las iniciativas de este órgano.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': True,
                  'tutor': False,
                  'inspector': False
                  },
                 {'subsub': 'Participación en los órganos de gobierno',
                  'preg': 'Realiza propuestas para la elaboración, modificación y actualización de los documentos generales del centro: programación general anual (criterios pedagógicos para la elaboración de horarios, necesidades de equipamiento, etc.), proyecto educativo de centro, plan de convivencia, reglamento de organización y funcionamiento, etc.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': True,
                  'tutor': False,
                  'inspector': False
                  },
                 {'subsub': 'Participación en los órganos de coordinación docente',
                  'preg': 'Coordina y participa activamente en la elaboración de la programación didáctica del departamento, de acuerdo con los criterios fijados por la comisión de coordinación pedagógica y con las directrices generales del proyecto educativo.',
                  'docente': False,
                  'docente-jefe': True,
                  'docente-tutor': False,
                  'orientador': False, 'director': True,
                  'tutor': False,
                  'inspector': False
                  },
                 {'subsub': 'Participación en los órganos de coordinación docente',
                  'preg': 'Convoca y prepara las reuniones del departamento; deja constancia escrita de los acuerdos alcanzados;  hace el seguimiento de los mismos; comenta con los profesores del departamento la marcha del curso y propone, si es necesario, cambios en la programación para adaptarla a las necesidades observadas.',
                  'docente': False,
                  'docente-jefe': True,
                  'docente-tutor': False,
                  'orientador': False, 'director': True,
                  'tutor': False,
                  'inspector': False
                  },
                 {'subsub': 'Participación en los órganos de coordinación docente',
                  'preg': 'En su caso, coordina y asume las tareas fijadas por el departamento para la atención de los alumnos con necesidades específicas de apoyo educativo programadas en colaboración con los servicios de apoyo.',
                  'docente': False,
                  'docente-jefe': True,
                  'docente-tutor': False,
                  'orientador': False, 'director': True,
                  'tutor': False,
                  'inspector': False
                  },
                 {'subsub': 'Participación en los órganos de coordinación docente',
                  'preg': 'Participa activamente en las reuniones de la comisión de coordinación pedagógica aportando iniciativas y sugerencias –tanto propias como de sus compañeros- para el cumplimiento de sus competencias, e informa a los miembros de su departamento de las resoluciones aprobadas.',
                  'docente': False,
                  'docente-jefe': True,
                  'docente-tutor': False,
                  'orientador': False, 'director': True,
                  'tutor': False,
                  'inspector': False
                  },
                 {'subsub': 'Participación en los órganos de coordinación docente',
                  'preg': 'Coordina y asume las tareas relativas a la organización de los espacios e instalaciones, así como la adquisición del material didáctico y científico (destinado a profesores y alumnos) necesario para el departamento; tomando iniciativas para facilitar su uso.',
                  'docente': False,
                  'docente-jefe': True,
                  'docente-tutor': False,
                  'orientador': False, 'director': True,
                  'tutor': False,
                  'inspector': False
                  },
                 {'subsub': 'Participación en los órganos de coordinación docente',
                  'preg': 'Participa activamente en la elaboración de la programación didáctica del departamento.',
                  'docente': True,
                  'docente-jefe': False,
                  'docente-tutor': True,
                  'orientador': False, 'director': True,
                  'tutor': False,
                  'inspector': False
                  },
                 {'subsub': 'Participación en los órganos de coordinación docente',
                  'preg': 'Participa activamente en la elaboración de las programaciones didácticas, en todo lo referente a la atención a la diversidad.',
                  'docente': False,
                  'docente-jefe': False,
                  'docente-tutor': False,
                  'orientador': True, 'director': True,
                  'tutor': False,
                  'inspector': False
                  },
                 {'subsub': 'Participación en los órganos de coordinación docente',
                  'preg': 'Participa activamente en las reuniones del departamento, comenta la marcha del curso y propone, si es necesario, cambios en la programación para adaptarla a las necesidades observadas.',
                  'docente': True,
                  'docente-jefe': False,
                  'docente-tutor': True,
                  'orientador': False, 'director': True,
                  'tutor': False,
                  'inspector': False
                  },
                 {'subsub': 'Participación en los órganos de coordinación docente',
                  'preg': 'Participa activamente en las reuniones de los órganos de coordinación docente,  comenta la marcha del curso y propone, si es necesario, cambios en la programación para adaptarla a las necesidades observadas.',
                  'docente': False,
                  'docente-jefe': False,
                  'docente-tutor': False,
                  'orientador': True, 'director': True,
                  'tutor': False,
                  'inspector': False
                  },
                 {'subsub': 'Participación en los órganos de coordinación docente',
                  'preg': 'En su caso, asume las tareas fijadas por el departamento para la atención de los alumnos con necesidades específicas de apoyo educativo.',
                  'docente': True,
                  'docente-jefe': False,
                  'docente-tutor': True,
                  'orientador': True, 'director': True,
                  'tutor': False,
                  'inspector': False
                  },
                 {'subsub': 'Participación en los órganos de coordinación docente',
                  'preg': 'Conoce las resoluciones adoptadas en la comisión de coordinación pedagógica y propone, a través del jefe del departamento, iniciativas sobre el desarrollo de sus funciones y competencias.',
                  'docente': True,
                  'docente-jefe': False,
                  'docente-tutor': True,
                  'orientador': True, 'director': True,
                  'tutor': False,
                  'inspector': False
                  },
                 {'subsub': 'Participación en los órganos de coordinación docente',
                  'preg': 'Hace propuestas sobre material de interés para el departamento, tanto del destinado a los alumnos como del que pueda favorecer la actualización didáctica y científica del profesorado, tomando iniciativas para facilitar su uso.',
                  'docente': True,
                  'docente-jefe': False,
                  'docente-tutor': True,
                  'orientador': False, 'director': True,
                  'tutor': False,
                  'inspector': False
                  },
                 {'subsub': 'Participación en los órganos de coordinación docente',
                  'preg': 'Hace propuestas sobre material de interés para los alumnos del centro, tanto del destinado a los alumnos como del que pueda favorecer la actualización didáctica y científica del profesorado, tomando iniciativas para facilitar su uso.',
                  'docente': False,
                  'docente-jefe': False,
                  'docente-tutor': False,
                  'orientador': True, 'director': True,
                  'tutor': False,
                  'inspector': False
                  },
                 {'subsub': 'Adopción de iniciativas para la mejora de la práctica docente y del trabajo en equipo',
                  'preg': 'Aporta datos y criterios de evaluación de su propia práctica docente y de la del departamento, promoviendo  que ésta se haga a través de la revisión de los elementos y desarrollo de la programación didáctica.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': False, 'director': True,
                  'tutor': False,
                  'inspector': False
                  },
                 {'subsub': 'Adopción de iniciativas para la mejora de la práctica docente y del trabajo en equipo',
                  'preg': 'Aporta datos y criterios de evaluación de su propia práctica docente, promoviendo que ésta se haga a través de la revisión de los elementos y desarrollo de las unidades de intervención.',
                  'docente': False,
                  'docente-jefe': False,
                  'docente-tutor': False,
                  'orientador': True, 'director': True,
                  'tutor': False,
                  'inspector': False
                  },
                 {'subsub': 'Adopción de iniciativas para la mejora de la práctica docente y del trabajo en equipo',
                  'preg': 'Promueve la participación en diversas iniciativas de mejora y de trabajo en equipo, tanto en programas institucionales  como en otros,  así como el intercambio de experiencias sobre aspectos didácticos con otros profesores.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': True,
                  'tutor': False,
                  'inspector': False
                  },
                 {'subsub': 'Adopción de iniciativas para la mejora de la práctica docente y del trabajo en equipo',
                  'preg': 'Promueve la participación del departamento en actividades de formación: haciendo propuestas de grupos de trabajo, aportando información de cursos que puedan ser de interés, etc.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': False, 'director': True,
                  'tutor': False,
                  'inspector': False
                  },
                 {'subsub': 'Adopción de iniciativas para la mejora de la práctica docente y del trabajo en equipo',
                  'preg': 'Promueve la participación en actividades de formación: haciendo propuestas de grupos de trabajo, aportando información de cursos que puedan ser de interés, etc.',
                  'docente': False,
                  'docente-jefe': False,
                  'docente-tutor': False,
                  'orientador': True, 'director': True,
                  'tutor': False,
                  'inspector': False
                  }
             ]},
         {
             'subdim': 'Colaboración y puesta en marcha de actividades extraescolares y de cualesquiera otras que dinamicen la vida del centro y que contribuyan al aprovechamiento de los recursos del entorno.',
             'valor': 4,
             'pregs': [
                 {'subsub': '',
                  'preg': 'Presenta propuestas y participa en la organización de la biblioteca escolar, en colaboración con la jefatura de estudios.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': True,
                  'tutor': False,
                  'inspector': False
                  },
                 {'subsub': '',
                  'preg': 'Propone, planifica y asume la realización de actividades complementarias y extraescolares, incluyéndolas en la programación didáctica, en su caso.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': True,
                  'tutor': False,
                  'inspector': False
                  },
                 {'subsub': '',
                  'preg': 'Prepara las visitas con el grupo clase y, cuando sea necesario, con los padres, presentándolas e informando de los objetivos de la actividad y de su relación con el resto de las actividades.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': True,
                  'tutor': False,
                  'inspector': False
                  },
                 {'subsub': '',
                  'preg': 'Elabora y/o utiliza guías didácticas, documentación y, en general, los recursos didácticos convenientes, planifica tareas que deben realizar los alumnos durante las actividades complementarias y valora su esfuerzo y grado de participación.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': True,
                  'tutor': False,
                  'inspector': False
                  }
             ]},
         {'subdim': 'Atención a padres y alumnos y, en su caso, ejercicio de la tutoría.',
          'valor': 4,
          'pregs': [
              {'subsub': '',
               'preg': 'Se muestra disponible para atender las demandas de los alumnos, incluso fuera de clase.',
               'docente': False,
               'docente-jefe': False,
               'docente-tutor': True,
               'orientador': False, 'director': True,
               'tutor': False,
               'inspector': False
               },
              {'subsub': '',
               'preg': 'Informa por escrito, al menos tres veces en el curso, a los padres de los alumnos sobre el aprovechamiento académico de estos y la marcha de su proceso educativo, orientándolos, cuando sea preciso, en los procesos de reclamación.',
               'docente': False,
               'docente-jefe': False,
               'docente-tutor': True,
               'orientador': False, 'director': True,
               'tutor': False,
               'inspector': False
               },
              {'subsub': '',
               'preg': 'Identifica las dificultades de aprendizaje y adopta las medidas de carácter general correspondientes (técnicas de estudio, orientaciones, etc.).',
               'docente': False,
               'docente-jefe': False,
               'docente-tutor': True,
               'orientador': False, 'director': True,
               'tutor': False,
               'inspector': False
               },
              {'subsub': '',
               'preg': 'Toma las iniciativas necesarias para facilitar la integración de cada alumno en su grupo y de éste en las actividades del centro.',
               'docente': False,
               'docente-jefe': False,
               'docente-tutor': True,
               'orientador': False, 'director': True,
               'tutor': False,
               'inspector': False
               },
              {'subsub': '',
               'preg': 'Facilita y lleva a cabo -tanto por iniciativa propia como por demanda de los padres- entrevistas y reuniones, tanto individuales como colectivas, a fin de informarles sobre el funcionamiento del centro y la marcha académica de sus hijos.',
               'docente': False,
               'docente-jefe': False,
               'docente-tutor': True,
               'orientador': False, 'director': True,
               'tutor': False,
               'inspector': False
               },
              {'subsub': '',
               'preg': 'Toma iniciativas para abordar, junto con los padres, aspectos tales como la creación de hábitos de autonomía y responsabilidad en los alumnos.',
               'docente': False,
               'docente-jefe': False,
               'docente-tutor': True,
               'orientador': False, 'director': True,
               'tutor': False,
               'inspector': False
               },
              {'subsub': '',
               'preg': 'Cumple el plan de acción tutorial, siguiendo las directrices del jefe de estudios y de los profesionales  del departamento de orientación.',
               'docente': False,
               'docente-jefe': False,
               'docente-tutor': True,
               'orientador': False, 'director': True,
               'tutor': False,
               'inspector': False
               },
              {'subsub': '',
               'preg': 'A lo largo del curso lleva a cabo, de manera sistemática, actividades para la organización del aula (distribución de responsabilidades, informaciones de interés para los alumnos, resolución de conflictos, establecimiento de normas de convivencia, etc.)',
               'docente': False,
               'docente-jefe': False,
               'docente-tutor': True,
               'orientador': False, 'director': True,
               'tutor': False,
               'inspector': False
               },
              {'subsub': '',
               'preg': 'Realiza el seguimiento periódico y sistemático de las faltas de puntualidad y asistencia de sus alumnos, interesándose por los motivos e informando a sus padres y, en su caso, profesores, oportunamente.',
               'docente': False,
               'docente-jefe': False,
               'docente-tutor': True,
               'orientador': False, 'director': True,
               'tutor': False,
               'inspector': False
               },
              {'subsub': '',
               'preg': 'Coordina las sesiones de evaluación y elabora, custodia y facilita los informes derivados de las mismas.',
               'docente': False,
               'docente-jefe': False,
               'docente-tutor': True,
               'orientador': False, 'director': True,
               'tutor': False,
               'inspector': False
               },
              {'subsub': '',
               'preg': 'Propicia el análisis y la reflexión sobre los resultados de la evaluación , informando a padres y alumnos sobre las medidas adoptadas en la sesión correspondiente.',
               'docente': False,
               'docente-jefe': False,
               'docente-tutor': True,
               'orientador': False, 'director': True,
               'tutor': False,
               'inspector': False
               },
              {'subsub': '',
               'preg': 'Coordina el equipo docente en la adopción, aplicación y seguimiento de medidas de apoyo para las dificultades del aprendizaje y de cuantos acuerdos se hayan tomado, no sólo en las sesiones de evaluación, sino también mediante contactos y reuniones periódicas, convocadas a tal efecto, con los distintos profesores del grupo.',
               'docente': False,
               'docente-jefe': False,
               'docente-tutor': True,
               'orientador': False, 'director': True,
               'tutor': False,
               'inspector': False
               },
              {'subsub': '',
               'preg': 'Tiene iniciativa y colabora, en su caso, con los profesionales del departamento de orientación.',
               'docente': False,
               'docente-jefe': False,
               'docente-tutor': True,
               'orientador': False, 'director': True,
               'tutor': False,
               'inspector': False
               },
              {'subsub': '',
               'preg': 'Es mediador y facilitador de las relaciones entre las familias, el profesorado y el centro escolar.',
               'docente': False,
               'docente-jefe': False,
               'docente-tutor': True,
               'orientador': False, 'director': True,
               'tutor': False,
               'inspector': False
               },
              {'subsub': '',
               'preg': 'Durante su permanencia en el centro, muestra disposición para atender las necesidades del mismo (sustituciones, proyectos, apoyos, etc.)',
               'docente': False,
               'docente-jefe': False,
               'docente-tutor': True,
               'orientador': False, 'director': True,
               'tutor': False,
               'inspector': False
               },
              {'subsub': '',
               'preg': 'Se muestra disponible para atender las demandas de los alumnos, incluso fuera de clase.',
               'docente': True,
               'docente-jefe': True,
               'docente-tutor': False,
               'orientador': True, 'director': True,
               'tutor': False,
               'inspector': False
               },
              {'subsub': '',
               'preg': 'Proporciona, en su caso,  a los tutores los datos necesarios para que puedan informar por escrito, al menos tres veces en el curso, a los padres sobre el aprovechamiento académico de los alumnos y la marcha de su proceso educativo.',
               'docente': True,
               'docente-jefe': True,
               'docente-tutor': False,
               'orientador': True, 'director': True,
               'tutor': False,
               'inspector': False
               },
              {'subsub': '',
               'preg': 'Identifica las dificultades de aprendizaje y adopta las medidas de carácter general correspondientes (técnicas de estudio, orientaciones, etc.).',
               'docente': True,
               'docente-jefe': True,
               'docente-tutor': False,
               'orientador': True, 'director': True,
               'tutor': False,
               'inspector': False
               },
              {'subsub': '',
               'preg': 'Participa activamente en las reuniones de padres convocadas por los tutores de los grupos de sus alumnos y proporciona información y orientación sobre las áreas que imparte.',
               'docente': True,
               'docente-jefe': True,
               'docente-tutor': False,
               'orientador': True, 'director': True,
               'tutor': False,
               'inspector': False
               },
              {'subsub': '',
               'preg': 'Informa a los padres de las horas en las que está disponible, atiende sus demandas y propicia el contacto con ellos para resolver las dificultades de sus hijos, informándoles sobre su marcha académica y las medidas adoptadas.',
               'docente': True,
               'docente-jefe': True,
               'docente-tutor': False,
               'orientador': True, 'director': True,
               'tutor': False,
               'inspector': False
               },
              {'subsub': '',
               'preg': 'Asume las medidas que se adoptan en las sesiones de evaluación, (adaptaciones, medidas de refuerzo, decisiones de promoción...).',
               'docente': True,
               'docente-jefe': True,
               'docente-tutor': False,
               'orientador': True, 'director': True,
               'tutor': False,
               'inspector': False
               },
              {'subsub': '',
               'preg': 'Durante su permanencia en el centro, muestra disposición para atender las necesidades del mismo (sustituciones, proyectos, apoyos, etc.)',
               'docente': True,
               'docente-jefe': True,
               'docente-tutor': False,
               'orientador': True, 'director': True,
               'tutor': False,
               'inspector': False
               }
          ]}
     ]},
    {'dim': 'ACTIVIDAD DOCENTE DENTRO DEL AULA',
     'subdims': [
         {
             'subdim': 'Preparación de la clase y de los materiales didácticos en el marco de las decisiones  adoptadas en la programación didáctica.',
             'valor': 6,
             'pregs': [
                 {'subsub': '',
                  'preg': 'Planifica el desarrollo de las unidades didácticas o de programación, organizándolas a lo largo del curso con una distribución adecuada, incluyendo actividades que se ajusten a las características de cada grupo (nivel de conocimientos previos, sus intereses, etc.).',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': False, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Planifica el desarrollo de las actuaciones, organizándolas a lo largo del curso con una distribución adecuada, incluyendo actividades que se ajusten a las características de cada grupo (nivel de conocimientos previos, sus intereses, etc.).',
                  'docente': False,
                  'docente-jefe': False,
                  'docente-tutor': False,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Planifica el desarrollo de las clases de modo flexible, teniendo en cuenta y preparando los materiales didácticos –ajustados a las características de sus alumnos y a la metodología escogida en cada momento-, previendo los medios (organización de espacios y recursos) que se van a necesitar, así como las correspondientes normas de uso, instalaciones y guías que se consideren precisas.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': False, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Planifica el desarrollo de las actividades de modo flexible, teniendo en cuenta y preparando los materiales (ajustados a las características de los alumnos y a la metodología escogida en cada momento), previendo los medios (organización de espacios y recursos) que se van a necesitar, así como las correspondientes normas de uso, instalaciones y guías que se consideren precisas.',
                  'docente': False,
                  'docente-jefe': False,
                  'docente-tutor': False,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Prevé y planifica a lo largo del curso la utilización de recursos externos al aula que requiere el área que imparte: trabajos de campo, museos, visitas a instalaciones de diversos tipos, contactos con agentes externos, etc.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': False, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Prevé y planifica a lo largo del curso la utilización de recursos externos al aula: trabajos de campo, museos, visitas a instalaciones de diversos tipos, contactos con agentes externos, etc.',
                  'docente': False,
                  'docente-jefe': False,
                  'docente-tutor': False,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Dispone de documentos (diario de clase, programación de cada sesión, cuaderno de notas o registro de observación) que le permiten realizar la planificación diaria y el seguimiento de la marcha de las clases en sus aspectos más significativos.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Plantea  las clases de forma coherente con el conjunto de la programación didáctica y, más concretamente, con la unidad didáctica o de trabajo de la que forma parte y los contenidos previstos son relevantes y significativos.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': False, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Plantea  las actuaciones de forma coherente con el conjunto de la programación.',
                  'docente': False,
                  'docente-jefe': False,
                  'docente-tutor': False,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  }
             ]},
         {
             'subdim': 'Utilización de una metodología de enseñanza adecuada para promover el aprendizaje significativo de los contenidos escolares.',
             'valor': 6,
             'pregs': [
                 {'subsub': '',
                  'preg': 'Presenta un plan de trabajo a los alumnos, antes de cada unidad didáctica o de programación y, en general, cuida de que no se pierda el contexto ni la visión de conjunto en cada sesión.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': False, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Presenta un plan de trabajo a los alumnos, antes de cada intervención  y, en general, cuida de que no se pierda el contexto ni la visión de conjunto en cada sesión.',
                  'docente': False,
                  'docente-jefe': False,
                  'docente-tutor': False,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Toma iniciativas que le permiten conocer los intereses y conocimientos previos de sus alumnos, adoptando medidas para motivarlos.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Utiliza la metodología establecida en la programación didáctica, correspondiente a las características de los distintos grupos de alumnos.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': False, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Utiliza la metodología adaptada  a las características de los distintos grupos de alumnos.',
                  'docente': False,
                  'docente-jefe': False,
                  'docente-tutor': False,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Fomenta la adquisición de aquellas técnicas de estudio y de trabajo que son las propias de los contenidos de su área.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Plantea en clase unos contenidos bien estructurados y organizados de acuerdo con la programación, proponiendo actividades variadas que parten de situaciones o problemas reales, que impliquen la búsqueda de información, optando por un planteamiento globalizado cuando la situación lo requiera.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': False, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Plantea en sus actuaciones unos  contenidos bien estructurados y organizados de acuerdo con los planes de orientación, proponiendo actividades variadas que parten de situaciones o problemas reales, que impliquen la búsqueda de información, optando por un planteamiento globalizado cuando la situación lo requiera.',
                  'docente': False,
                  'docente-jefe': False,
                  'docente-tutor': False,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Integra en la correspondiente unidad didáctica o de programación los recursos didácticos que sean pertinentes: diferentes lenguajes, medios audiovisuales e informáticos, mapas, gráficos…etc.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': False, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Integra en la correspondiente unidad de intervención  los recursos didácticos que sean pertinentes: diferentes lenguajes, medios audiovisuales e informáticos, mapas, gráficos, etc.',
                  'docente': False,
                  'docente-jefe': False,
                  'docente-tutor': False,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Realiza actividades, individualizadas y/o en grupo, coherentes con los objetivos y las actividades planteados.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Revisa y replantea su planificación y, por lo tanto, sus estrategias, de acuerdo con la información obtenida en los procesos de evaluación de los alumnos y de la práctica docente.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  }
             ]},
         {
             'subdim': 'Procedimientos de evaluación de los aprendizajes e información sobre los mismos que se da a los alumnos y a sus familias.',
             'valor': 6,
             'pregs': [
                 {'subsub': ' Procedimientos de evaluación',
                  'preg': 'Solicita, a comienzo de curso,  información sobre sus alumnos al tutor del curso anterior, así como a aquellos profesores que puedan disponer de información relevante sobre los mismos.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': False, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': ' Procedimientos de evaluación',
                  'preg': 'Solicita, a comienzo de curso, información sobre los alumnos al tutor del curso anterior, así como a aquellos profesores que puedan disponer de información relevante sobre los mismos.',
                  'docente': False,
                  'docente-jefe': False,
                  'docente-tutor': False,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': ' Procedimientos de evaluación',
                  'preg': 'Realiza una evaluación inicial, bien general, bien referida a una unidad didáctica o de programación, que luego utiliza como punto de partida para ajustar la programación.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': False, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': ' Procedimientos de evaluación',
                  'preg': 'Realiza una evaluación inicial, que luego utiliza como punto de partida para ajustar su intervención en el aula.',
                  'docente': False,
                  'docente-jefe': False,
                  'docente-tutor': False,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': ' Procedimientos de evaluación',
                  'preg': 'Corrige y explica los trabajos y actividades, favoreciendo la autoevaluación.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': ' Procedimientos de evaluación',
                  'preg': 'Participa activamente en todas las sesiones de evaluación, aporta información relevante y toma en consideración la información proporcionada por los otros profesores.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': ' Procedimientos de evaluación',
                  'preg': 'Adopta unos criterios de evaluación que tienen en cuenta la graduación con la que se deben alcanzar los objetivos y contenidos seleccionados y tiene en cuenta la especial atención al alumnado con necesidad específica de apoyo educativo.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': ' Procedimientos de evaluación',
                  'preg': 'Aplica los criterios de calificación establecidos en la programación didáctica.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': ' Instrumentos de evaluación utilizados por el profesor',
                  'preg': 'Emplea unos instrumentos de evaluación adecuados a los contenidos que pretende evaluar y al grado de madurez del alumnado, de acuerdo con los criterios de evaluación del área.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': ' Instrumentos de evaluación utilizados por el profesor',
                  'preg': 'Utiliza instrumentos variados y adecuados a los distintos contenidos, de tal manera que permitan contrastar los resultados y los diferentes grados de aprendizaje que han alcanzado los alumnos.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': 'Instrumentos de evaluación utilizados por el profesor',
                  'preg': 'Elabora instrumentos de evaluación específicos, coherentes con los criterios de evaluación formulados, para alumnos con necesidad de adaptaciones, con necesidad específica de apoyo educativo, etc.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': 'Información sobre evaluación',
                  'preg': 'Utiliza adecuadamente los modelos de información para las familias establecidos por el centro para recoger, tres veces por curso, los logros y dificultades de los alumnos.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': 'Información sobre evaluación',
                  'preg': 'Utiliza adecuadamente los modelos establecidos por el centro para recoger a lo largo de la etapa los datos más relevantes sobre el aprendizaje de los alumnos en relación con los objetivos y criterios de evaluación de las distintas áreas.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': 'Información sobre evaluación',
                  'preg': 'Establece los medios que garanticen que los alumnos conozcan, en todo momento, los progresos y dificultades sobre su proceso de aprendizaje.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  }
             ]},
         {
             'subdim': 'Utilización de medidas ordinarias y extraordinarias para atender a la diversidad de capacidades, intereses y motivaciones de los alumnos, especialmente de aquéllos con mayores dificultades de aprendizaje.',
             'valor': 6,
             'pregs': [
                 {'subsub': '',
                  'preg': 'Adopta medidas de apoyo a las deficiencias de aprendizaje, tanto preventivas como de corrección o ayuda, hace el seguimiento y evalúa los resultados.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Toma medidas para facilitar el aprendizaje de las cuestiones que habitualmente ofrecen mayores dificultades, así como para que puedan profundizar los alumnos con un ritmo de aprendizaje más rápido.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Utiliza diferentes estrategias metodológicas en función de las características e intereses de los alumnos, materiales didácticos graduados en función de su dificultad y ajusta el desarrollo temporal de la programación a los diferentes ritmos de los alumnos.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Tiene criterios claros relativos a las causas y el momento en el que debe llevar a cabo una propuesta de adaptación curricular.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Elabora las adaptaciones curriculares para los alumnos que las precisen (en colaboración con los servicios de apoyo con los que cuenta), asume su aplicación, hace el seguimiento recogiendo documentalmente la selección de contenidos, las modificaciones metodológicas y de evaluación que se realicen.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': False, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Elabora las adaptaciones curriculares para los alumnos que las precisen, asume su aplicación, hace el seguimiento recogiendo documentalmente la selección de contenidos, las modificaciones metodológicas y de evaluación que se realicen.',
                  'docente': False,
                  'docente-jefe': False,
                  'docente-tutor': False,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Tiene fijados los materiales, lugar, hora y agrupamientos de los alumnos a los que aplica las distintas medidas de atención a la diversidad, revisa y adecua las adaptaciones previstas a la realidad de sus alumnos.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Realiza propuestas sobre la modificación o adquisiciones de recursos materiales que permitan adecuarlos a los alumnos con necesidades específicas.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Colabora con el profesorado de apoyo a la integración y, en su caso, con el orientador.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': False, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Colabora con el profesorado de apoyo a la integración.',
                  'docente': False,
                  'docente-jefe': False,
                  'docente-tutor': False,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  }
             ]},
         {
             'subdim': 'Organización del trabajo en el aula para favorecer la adecuada marcha de la clase y la participación e implicación del alumnado en su proceso de aprendizaje.',
             'valor': 6,
             'pregs': [
                 {'subsub': '',
                  'preg': 'Consigue que las relaciones entre los alumnos dentro del aula y de estos con el profesor, sean correctas y fluidas, y se plantean desde una perspectiva no discriminatoria.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Favorece la elaboración de normas de convivencia con la aportación de todos y reacciona de forma ecuánime, adecuada e inmediata, ante situaciones inesperadas o conflictivas.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Fomenta la participación, el respeto y la colaboración entre los alumnos y acepta, de buen grado, sus sugerencias y aportaciones.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Plantea la clase con un ritmo de progresión adecuado y con tiempos suficientes para las distintas actividades.',
                  'docente': True,
                  'docente-jefe': True,
                  'docente-tutor': True,
                  'orientador': False, 'director': False,
                  'tutor': True,
                  'inspector': True
                  },
                 {'subsub': '',
                  'preg': 'Plantea la intervención en el aula  con un ritmo de progresión adecuado y con tiempos suficientes para las distintas actividades.',
                  'docente': False,
                  'docente-jefe': False,
                  'docente-tutor': False,
                  'orientador': True, 'director': False,
                  'tutor': True,
                  'inspector': True
                  }
             ]}
     ]}
]
