Menus_Centro_Educativo = [('acceso_configuracion', 'Configuración', 1),
                          ('acceso_perfiles_permisos', 'Establecer perfiles y permisos a usuarios', 1),
                          ('acceso_datos_entidad', 'Datos de la entidad', 1),
                          ('acceso_redactar_mensaje', 'Redactar mensaje', 1),
                          ('acceso_vista_calendario', 'Vista calendario', 1),
                          ('acceso_documentos', 'Documentos', 1),
                          ('acceso_carga_masiva_horarios', 'Carga masiva horarios', 1),
                          ('acceso_cupo_profesorado', 'Cupo de profesores', 1),
                          ('acceso_absentismo', 'Absentismo', 1),
                          ('acceso_gestionar_conductas', 'Establecer conductas y sanciones', 1),
                          ('acceso_informes_seguimiento', 'Informe de seguimiento', 1),
                          ('acceso_noticias_web', 'Noticias WEB', 1),
                          ('acceso_configura_cursos', 'Configuración de cursos', 1),
                          ('cc_valorar_mis_alumnos', 'Valorar a mis alumnos', 1),
                          ('acceso_programaciones_ccff', 'Programaciones CCFF', 1),
                          ('acceso_conv_template', 'Plantillas de convocatorias', 1),
                          ('acceso_grupos_domotica', 'Agrupaciones de dispositivos', 1),
                          ('acceso_gestionar_perfiles', 'Crear Perfiles/Cargos/Organigrama', 2),
                          ('acceso_gestion_entidad', 'Equipo directivo', 2),
                          ('acceso_crear_usuarios', 'Añadir un nuevo usuario', 2),
                          ('acceso_mensajes_enviados', 'Mensajes enviados', 2),
                          ('acceso_define_horarios', 'editar horarios', 2),
                          ('acceso_reparaciones', 'Reparaciones', 2),
                          ('acceso_sancionar_conductas', 'Sancionar conductas', 2),
                          ('acceso_informes_tareas', 'Informe con tareas', 2),
                          ('acceso_configura_grupos', 'Configuración de grupos', 2),
                          ('cc_valorar_cualquier_alumno', 'Valorar a cualquier alumno', 2),
                          ('acceso_resultados_aprendizaje', 'Resultados de aprendizaje', 2),
                          ('acceso_conv_reunion', 'Realizar convocatorias', 2),
                          ('acceso_configura_domotica', 'Configurar domótica', 2),
                          ('acceso_carga_masiva', 'Carga masiva', 3),
                          ('acceso_getion_bajas', 'Gestión de bajas', 3),
                          ('acceso_mensajes', 'Correo y mensajería', 3),
                          ('acceso_mensajes_recibidos', 'Mensajes recibidos', 3),
                          ('acceso_actividades_horarios', 'Actividades del horario', 3),
                          ('acceso_expediente_sancionador', 'Expediente sancionador', 3),
                          ('acceso_actividades', 'Actividades extraescolares', 3),
                          ('acceso_cuerpos_funcionarios', 'Cuerpos de funcionarios', 3),
                          ('acceso_configura_pendientes', 'Configurar materias pendientes', 3),
                          ('configura_ccs', 'Ponderar competencias clave', 3),
                          ('acceso_redactar_actas_reunion', 'Redactar actas', 3),
                          ('acceso_gestionar_subentidades', 'Departamentos/Secciones', 4),
                          ('acceso_reserva_plazas', 'Reserva de plazas', 4),
                          ('acceso_calendario', 'Calendario', 4),
                          ('acceso_cargar_programaciones', 'Cargar programaciones', 4),
                          ('acceso_evaluar_materias', 'Evaluación de pendientes', 4),
                          ('acceso_control_asistencia_reunion', 'Control de asistencia', 4),
                          ('acceso_miembros_entidad', 'Personas en el iES', 5),
                          ('acceso_gestion_documental', 'Gestión documental', 5),
                          ('acceso_profesores_centro_educativo', 'Profesores del centro', 5),
                          ('acceso_firmar_actas_reunion', 'Firmar actas', 5),
                          ('acceso_listados_usuarios', 'Listados de usuarios', 6),
                          ('acceso_horarios', 'Horarios', 6),
                          ('acceso_lectura_actas_reunion', 'Leer actas', 6),
                          ('acceso_aspectos_pga', 'Aspectos generales de la PGA', 6),
                          ('acceso_horario_usuarios', 'Horarios profesores', 7),
                          ('acceso_cupos', 'Cupos IES', 7),
                          ('acceso_dependencias_entidad', 'Dependencias', 7),
                          ('acceso_pec', 'Proyecto Educativo del Centro', 7),
                          ('acceso_horarios_subentidades', 'Horarios grupos', 8),
                          ('acceso_gestionar_rondas', 'cursos escolares', 8),
                          ('acceso_acciones_usuarios1', 'Acciones DOCENTES', 8),
                          ('acceso_departamentos_centro_educativo', 'Departamentos del centro', 8),
                          ('acceso_registro', 'Registro', 9),
                          ('acceso_convivencia', 'Convivencia', 9),
                          ('acceso_horario_aulas', 'Horarios aulas', 9),
                          ('acceso_guardias_horarios', 'Guardias profesores', 10),
                          ('acceso_informes_usuarios', 'Informes', 10),
                          ('acceso_doc_configuration', 'Configuración de documentos', 10),
                          ('acceso_tutores_entidad', 'Tutores', 11),
                          ('acceso_web', 'página WEB', 11),
                          ('acceso_seguimiento_educativo', 'Seguimiento educativo', 11),
                          ('acceso_actillas', 'Actillas', 12),
                          ('acceso_estudios_centro_educativo', 'Configuración de estudios', 12),
                          ('acceso_horarios_alumnos', 'Alumnos', 13),
                          ('acceso_competencias_clave', 'Competencias clave', 13),
                          ('acceso_programaciones_didacticas', 'Programaciones didácticas', 14),
                          ('acceso_reuniones', 'Reuniones', 15),
                          ('acceso_domotica', 'Domótica', 16),
                          ('acceso_inspeccion_educativa', 'Inspección Educativa', 17)]

TiposCentro = ['C.P.E.D. - Centro Privado Autorizado de Enseñanzas Deportivas',
               'C.P.E.I - Centro Privado de Educación Infantil',
               'C.E.P.A. - Centro Público de Educación de Personas Adultas',
               'C.E.E. - Centro de Educación Especial',
               'E.I.P.C.M. - Escuela Municipal de Educación Infantil',
               'C.R.A. - Colegio Rural Agrupado',
               'I.E.S. - Instituto de Educación Secundaria',
               'C.E.M. - Conservatorio Elemental de Música',
               'C.P.E.E. - Centro Privado de Educación Especial',
               'C.I.P.F.P. - Centro Público Integrado de Formación Profesional',
               'C.P.E.I.P. - Centro Privado de Educación Infantil y Primaria',
               'C.P.E.S. - Centro Privado de Educación Secundaria',
               'E.I.P.C. - Escuela Infantil',
               'C.E.I.P. - Colegio de Educación Infantil y Primaria',
               'C.P.F.P.E. - Centro Privado de Formación Profesional Específica',
               'C.P.E.I.P.S. - Centro Privado de Educación Infantil Primaria y Secundaria',
               'E.O.I. - Escuela Oficial de Idiomas',
               'C.P.M. - Conservatorio Profesional de Música',
               'C.P.F.P. - Centro Privado de Formación Profesional',
               'S.I.E.S. - Sección de Instituto de Educación Secundaria',
               'C.E.O. - Centro de Educación Obligatoria']
