Miembro_Equipo_Directivo = ['acceso_configuracion', 'acceso_perfiles_permisos', 'asigna_perfiles', 'asigna_permisos',
                            'modifica_texto_menu', 'modifica_pos_menu', 'acceso_datos_entidad',
                            'modifica_datos_entidad', 'crea_dependencias', 'borra_dependencias', 'acceso_mensajes',
                            'acceso_redactar_mensaje', 'redacta_cualquier_usuario', 'redacta_usuarios_departamentos',
                            'redacta_usuarios_1', 'redacta_usuarios_2', 'redacta_usuarios_3', 'redacta_usuarios_4',
                            'acceso_calendario', 'acceso_vista_calendario', 'crea_eventos', 've_todos_eventos',
                            'borra_cualquier_evento', 'acceso_gestion_documental', 'acceso_documentos', 'crea_carpetas',
                            'sube_archivos', 've_todas_carpetas', 'edita_todos_archivos', 'borra_cualquier_archivo',
                            'borra_cualquier_carpeta', 'acceso_cuestionarios', 'acceso_formularios', 'crea_formularios',
                            'acceso_horarios', 'acceso_cupos', 'acceso_cupo_profesorado', 'crea_cupos', 'edita_cupos',
                            'copia_cupo_profesorado', 'borra_cupo_profesorado', 'crea_materias_cupo', 'pdf_cupo',
                            'bloquea_cupos', 'acceso_acciones_usuarios1', 'acceso_convivencia',
                            'acceso_gestionar_conductas', 'edita_sanciones_tipificadas', 'edita_conductas_tipificadas',
                            'acceso_absentismo', 'crea_actuacion_absentismo', 'borra_actuacion_absentismo',
                            'edita_actuacion_absentismo', 'crea_informe_absentismo', 'configura_expediente_absentismo',
                            'acceso_registro', 'crea_registros', 'borra_registros', 'acceso_reparaciones',
                            'crea_solicitud_reparacion', 'borra_solicitud_reparacion', 'controla_reparaciones_alb',
                            'controla_reparaciones_car', 'controla_reparaciones_ele', 'controla_reparaciones_inf',
                            'controla_reparaciones_fon', 'controla_reparaciones_gen', 'controla_reparaciones',
                            'genera_informe_reparaciones', 'acceso_actividades', 'crea_actividad', 'borra_actividad',
                            'edita_actividades', 'crea_informe_actividades', 'aprueba_actividades',
                            'acceso_informes_usuarios', 'acceso_informes_seguimiento', 'solicita_informes_seguimiento',
                            'borra_informes_seguimiento', 'edita_informes_seguimiento', 've_informes_seguimiento',
                            'borra_preguntas_informes_seguimiento', 'acceso_estudios_centro_educativo',
                            'acceso_configura_cursos', 'crea_cursos', 'borra_cursos', 'acceso_competencias_clave',
                            'valora_ccs_a_cualquier_alumno', 'genera_informe_ccs', 'acceso_programaciones_didacticas',
                            'acceso_programaciones_ccff', 'crea_programaciones_ccff', 'edita_programaciones_ccff',
                            'copia_programaciones_ccff', 'borra_programaciones_ccff', 'acceso_evaluar_materias',
                            'evalua_materias_asignadas', 'evalua_cualquier_materia', 'acceso_reuniones',
                            'acceso_conv_template', 'c_conv_template', 'w_conv_template', 'd_conv_template',
                            'acceso_gestionar_perfiles', 'crea_perfiles', 'borra_perfiles', 'edita_perfiles',
                            'acceso_crear_usuarios', 'crea_usuarios', 'acceso_mensajes_enviados',
                            'acceso_sancionar_conductas', 'sancionar_nivel_docente', 'sancionar_nivel_tutor',
                            'sancionar_nivel_jefe_estudios', 'sancionar_nivel_director', 'borra_sanciones_tipificadas',
                            'borra_conductas_tipificadas', 'genera_informe_sancionador', 'elige_sancionador',
                            'borra_informes_sancionadores', 'aplica_cualquier_sancion',
                            'recibe_mensajes_aviso_informes_sancionadores', 'acceso_configura_grupos', 'crea_grupos',
                            'borra_grupos', 'cc_valorar_mis_alumnos', 'acceso_cargar_programaciones',
                            'carga_programaciones', 'borra_programaciones_cargadas', 'descarga_programaciones',
                            'descarga_pga', 'acceso_configura_pendientes', 'acceso_conv_reunion', 'r_conv_reunion',
                            'c_conv_reunion', 'w_conv_reunion', 'd_conv_reunion', 'm_conv_reunion',
                            'acceso_carga_masiva', 'sube_archivo_csv', 'carga_masiva_racima', 'acceso_gestion_entidad',
                            'acceso_getion_bajas', 'alta_usuarios', 'baja_usuarios', 'borra_usuarios',
                            'acceso_mensajes_recibidos', 'acceso_informes_tareas', 'solicita_informes_tareas',
                            'borra_informes_tareas', 'edita_informes_tareas', 've_informes_tareas',
                            'cc_valorar_cualquier_alumno', 'acceso_resultados_aprendizaje',
                            'crea_resultados_aprendizaje_ccff', 'borra_resultados_aprendizaje_ccff',
                            'crea_objetivos_ccff', 'borra_objetivos_ccff', 'acceso_redactar_actas_reunion',
                            'w_sus_actas_reunion', 'w_actas_subentidades_reunion', 'w_cualquier_acta_reunion',
                            'mail_actas_reunion', 'acceso_gestionar_subentidades', 'crea_subentidades',
                            'borra_subentidades', 'edita_subentidades', 'acceso_reserva_plazas', 'reserva_usuarios',
                            'recibe_aviso_reserva', 'acceso_define_horarios', 'crea_horarios', 'borra_horarios',
                            'acceso_cuerpos_funcionarios', 'configura_ccs', 'acceso_miembros_entidad',
                            'listado_usuarios', 'modifica_datos_usuarios', 'configura_auto_id',
                            'acceso_horario_usuarios', 've_horarios_usuarios', 'crea_sesiones_horario',
                            'borra_sesiones_horario', 'modifica_sesiones_horario', 'alumnos_sesiones_horario',
                            'crea_horarios_usuarios', 'acceso_departamentos_centro_educativo', 'borra_departamentos',
                            'recarga_departamentos', 'add_miembros_departamento', 'acceso_control_asistencia_reunion',
                            'acceso_firmar_actas_reunion', 'acceso_listados_usuarios', 'acceso_horario_aulas',
                            'acceso_profesores_centro_educativo', 'acceso_lectura_actas_reunion', 'r_actas_reunion',
                            'acceso_horarios_subentidades', 've_horarios_entidad', 'acceso_dependencias_entidad',
                            'acceso_aspectos_pga', 'acceso_carga_masiva_horarios', 'crea_rondas',
                            'acceso_gestionar_rondas', 'accede_otras_rondas', 'acceso_pec',
                            'acceso_actividades_horarios', 'crea_actividades_horario', 'borra_actividades_horario',
                            'edita_actividades_horario', 'acceso_guardias_horarios', 'crea_guardias_horario',
                            'borra_guardias_horario', 'edita_guardias_horario', 'acceso_horarios_alumnos',
                            'asigna_grupo_alumnos', 'asigna_tutor_alumnos', 'acceso_actillas', 'genera_actillas',
                            'acceso_tutores_entidad', 'acceso_inspeccion_educativa', 'acceso_actas_firmadas',
                            'sube_actas_evaluacion']

ESPECIALIDADES = (("031", "Educación Infantil", "597"),
                  ("032", "Inglés", "597"),
                  ("033", "Francés", "597"),
                  ("034", "Educación Física", "597"),
                  ("035", "Música", "597"),
                  ("036", "Pedagogía Terapéutica", "597"),
                  ("037", "Audición y Lenguaje", "597"),
                  ("038", "Educación Primaria", "597"),
                  ("001", "Filosofía", "590"),
                  ("002", "Griego", "590"),
                  ("003", "Latín", "590"),
                  ("004", "Lengua Castellana y Literatura", "590"),
                  ("005", "Geografía e Historia", "590"),
                  ("006", "Matemáticas", "590"),
                  ("007", "Física y Química", "590"),
                  ("008", "Biología y Geología", "590"),
                  ("009", "Dibujo", "590"),
                  ("010", "Francés", "590"),
                  ("011", "Inglés", "590"),
                  ("012", "Alemán", "590"),
                  ("013", "Italiano", "590"),
                  ("016", "Música", "590"),
                  ("017", "Educación Física", "590"),
                  ("018", "Orientación educativa (*)", "590"),
                  ("019", "Tecnología", "590"),
                  ("061", "Economía", "590"),
                  ("101", "Administración de Empresas", "590"),
                  ("102", "Análisis y Química Industrial", "590"),
                  ("103", "Asesoría y Procesos de Imagen Personal", "590"),
                  ("104", "Construcciones Civiles y Edificación", "590"),
                  ("105", "Formación y Orientación Laboral", "590"),
                  ("106", "Hostelería y Turismo", "590"),
                  ("107", "Informática", "590"),
                  ("108", "Intervención Socio-comunitaria", "590"),
                  ("109", "Navegación e Instalaciones Marinas", "590"),
                  ("110", "Organización y Gestión Comercial", "590"),
                  ("111", "Organización y Procesos de Mantenimiento de Vehículos", "590"),
                  ("112", "Organización y Proyectos de Fabricación Mecánica", "590"),
                  ("113", "Organización y Proyectos de Sistemas Energéticos", "590"),
                  ("114", "Procesos de Cultivo Acuícola", "590"),
                  ("115", "Procesos de Producción Agraria", "590"),
                  ("116", "Procesos en la Industria Alimentaria", "590"),
                  ("117", "Procesos Diagnósticos Clínicos y Procedimientos Ortoprotésicos", "590"),
                  ("118", "Procesos Sanitarios", "590"),
                  ("119", "Procesos y Medios de Comunicación", "590"),
                  ("120", "Procesos y Productos de Textil, Confección y Piel", "590"),
                  ("121", "Procesos y Productos de Vidrio y Cerámica", "590"),
                  ("122", "Procesos y Productos en Artes Gráficas", "590"),
                  ("123", "Procesos y Productos en Madera y Mueble", "590"),
                  ("124", "Sistemas Electrónicos", "590"),
                  ("125", "Sistemas Electrotécnicos y Automáticos", "590"),
                  ("803", "Cultura Clásica", "590"),
                  ("001", "Filosofía", "511"),
                  ("002", "Griego", "511"),
                  ("003", "Latín", "511"),
                  ("004", "Lengua Castellana y Literatura", "511"),
                  ("005", "Geografía e Historia", "511"),
                  ("006", "Matemáticas", "511"),
                  ("007", "Física y Química", "511"),
                  ("008", "Biología y Geología", "511"),
                  ("009", "Dibujo", "511"),
                  ("010", "Francés", "511"),
                  ("011", "Inglés", "511"),
                  ("012", "Alemán", "511"),
                  ("013", "Italiano", "511"),
                  ("016", "Música", "511"),
                  ("017", "Educación Física", "511"),
                  ("018", "Orientación educativa (*)", "511"),
                  ("019", "Tecnología", "511"),
                  ("061", "Economía", "511"),
                  ("101", "Administración de Empresas", "511"),
                  ("102", "Análisis y Química Industrial", "511"),
                  ("103", "Asesoría y Procesos de Imagen Personal", "511"),
                  ("104", "Construcciones Civiles y Edificación", "511"),
                  ("105", "Formación y Orientación Laboral", "511"),
                  ("106", "Hostelería y Turismo", "511"),
                  ("107", "Informática", "511"),
                  ("108", "Intervención Socio-comunitaria", "511"),
                  ("109", "Navegación e Instalaciones Marinas", "511"),
                  ("110", "Organización y Gestión Comercial", "511"),
                  ("111", "Organización y Procesos de Mantenimiento de Vehículos", "511"),
                  ("112", "Organización y Proyectos de Fabricación Mecánica", "511"),
                  ("113", "Organización y Proyectos de Sistemas Energéticos", "511"),
                  ("114", "Procesos de Cultivo Acuícola", "511"),
                  ("115", "Procesos de Producción Agraria", "511"),
                  ("116", "Procesos en la Industria Alimentaria", "511"),
                  ("117", "Procesos Diagnósticos Clínicos y Procedimientos Ortoprotésicos", "511"),
                  ("118", "Procesos Sanitarios", "511"),
                  ("119", "Procesos y Medios de Comunicación", "511"),
                  ("120", "Procesos y Productos de Textil, Confección y Piel", "511"),
                  ("121", "Procesos y Productos de Vidrio y Cerámica", "511"),
                  ("122", "Procesos y Productos en Artes Gráficas", "511"),
                  ("123", "Procesos y Productos en Madera y Mueble", "511"),
                  ("124", "Sistemas Electrónicos", "511"),
                  ("125", "Sistemas Electrotécnicos y Automáticos", "511"),
                  ("803", "Cultura Clásica", "511"),
                  ("201", "Cocina y Pastelería", "591"),
                  ("202", "Equipos Electrónicos", "591"),
                  ("203", "Estética", "591"),
                  ("204", "Fabricación e Instalación de Carpintería y Mueble", "591"),
                  ("205", "Instalaciones y Mantenimiento de Equipos Térmicos y de Fluidos", "591"),
                  ("206", "Instalaciones Electrotécnicas", "591"),
                  ("207", "Instalaciones y Equipos de Cría y Cultivo", "591"),
                  ("208", "Laboratorio", "591"),
                  ("209", "Mantenimiento de Vehículos", "591"),
                  ("210", "Máquinas, Servicios y Producción", "591"),
                  ("211", "Mecanizado y Mantenimiento de Máquinas", "591"),
                  ("212", "Oficina de Proyectos de Construcción", "591"),
                  ("213", "Oficina de Proyectos y Fabricación Mecánica", "591"),
                  ("214", "Operaciones y Equipos de Elaboración de Productos Alimentarios", "591"),
                  ("215", "Operaciones de Procesos", "591"),
                  ("216", "Operaciones y Equipos de Producción Agraria", "591"),
                  ("217", "Patronaje y Confección", "591"),
                  ("218", "Peluquería", "591"),
                  ("219", "Procedimientos de Diagnóstico Clínico y Ortoprotésico", "591"),
                  ("220", "Procedimientos Sanitarios y Asistenciales", "591"),
                  ("221", "Procesos Comerciales", "591"),
                  ("222", "Procesos de Gestión Administrativa", "591"),
                  ("223", "Producción en Artes Gráficas", "591"),
                  ("224", "Producción Textil y Tratamiento Físico-Químicos", "591"),
                  ("225", "Servicios a la Comunidad", "591"),
                  ("226", "Servicios de Restauración", "591"),
                  ("227", "Sistemas y Aplicaciones Informáticos", "591"),
                  ("228", "Soldadura", "591"),
                  ("229", "Técnicas y Procedimientos de Imagen y Sonido", "591"),
                  ("001", "Alemán", "592"),
                  ("002", "Árabe", "592"),
                  ("006", "Español", "592"),
                  ("008", "Francés", "592"),
                  ("010", "Griego", "592"),
                  ("011", "Inglés", "592"),
                  ("012", "Italiano", "592"),
                  ("013", "Japonés", "592"),
                  ("015", "Portugués", "592"),
                  ("017", "Ruso", "592"),
                  ("001", "Alemán", "512"),
                  ("002", "Árabe", "512"),
                  ("006", "Español", "512"),
                  ("008", "Francés", "512"),
                  ("010", "Griego", "512"),
                  ("011", "Inglés", "512"),
                  ("012", "Italiano", "512"),
                  ("013", "Japonés", "512"),
                  ("015", "Portugués", "512"),
                  ("017", "Ruso", "512"),
                  ("002", "Armonía y Melodía Acompañada", "593"),
                  ("003", "Arpa", "593"),
                  ("005", "Ballet Clásico", "593"),
                  ("006", "Canto", "593"),
                  ("007", "Caracterización", "593"),
                  ("008", "Clarinete", "593"),
                  ("009", "Clave", "593"),
                  ("010", "Composición e Instrumentación", "593"),
                  ("013", "Conjunto Coral e Instrumental", "593"),
                  ("014", "Contrabajo", "593"),
                  ("015", "Contrapunto y Fuga", "593"),
                  ("017", "Danza Española", "593"),
                  ("021", "Dirección Coros y Conjunto Coral", "593"),
                  ("023", "Dirección de Orquesta y Conjunto Instrumental", "593"),
                  ("024", "Dramaturgia", "593"),
                  ("026", "Escenografía", "593"),
                  ("027", "Esgrima", "593"),
                  ("028", "Estética e Historia de la Música, Cultura y Arte", "593"),
                  ("029", "Expresión Corporal", "593"),
                  ("030", "Fagot", "593"),
                  ("031", "Flauta de Pico", "593"),
                  ("032", "Flauta Travesera", "593"),
                  ("035", "Guitarra", "593"),
                  ("037", "Historia de la Cultura y del Arte", "593"),
                  ("038", "Historia de la Literatura Dramática", "593"),
                  ("042", "Instrumentos de Pulso y Púa", "593"),
                  ("043", "Interpretación", "593"),
                  ("050", "Música de Cámara", "593"),
                  ("051", "Musicología", "593"),
                  ("052", "Oboe", "593"),
                  ("053", "Órgano", "593"),
                  ("055", "Ortofonía y Dicción", "593"),
                  ("058", "Percusión", "593"),
                  ("059", "Piano", "593"),
                  ("061", "Repentización, Transposición Instrumental y Acompañamiento", "593"),
                  ("066", "Saxofón", "593"),
                  ("068", "Solfeo y Teoría de la Música", "593"),
                  ("072", "Trombón", "593"),
                  ("074", "Trompa", "593"),
                  ("075", "Trompeta", "593"),
                  ("076", "Tuba", "593"),
                  ("077", "Viola", "593"),
                  ("078", "Violín", "593"),
                  ("079", "Violoncello", "593"),
                  ("402", "Arpa", "594"),
                  ("403", "Canto", "594"),
                  ("404", "Clarinete", "594"),
                  ("405", "Clave", "594"),
                  ("406", "Contrabajo", "594"),
                  ("407", "Coro", "594"),
                  ("408", "Fagot", "594"),
                  ("410", "Flauta Travesera", "594"),
                  ("411", "Flauta de Pico", "594"),
                  ("412", "Fundamentos de Composición", "594"),
                  ("414", "Guitarra", "594"),
                  ("415", "Guitarra Flamenca", "594"),
                  ("416", "Historia de la Música", "594"),
                  ("417", "Instrumento de Cuerda Pulsada del Renacimiento y del Barroco", "594"),
                  ("419", "Oboe", "594"),
                  ("420", "Órgano", "594"),
                  ("421", "Orquesta", "594"),
                  ("422", "Percusión", "594"),
                  ("423", "Piano", "594"),
                  ("424", "Saxofón", "594"),
                  ("426", "Trombón", "594"),
                  ("427", "Trompa", "594"),
                  ("428", "Trompeta", "594"),
                  ("429", "Tuba", "594"),
                  ("431", "Viola", "594"),
                  ("432", "Viola da Gamba", "594"),
                  ("433", "Violín", "594"),
                  ("434", "Violoncello", "594"),
                  ("435", "Danza Española", "594"),
                  ("436", "Danza Clásica", "594"),
                  ("437", "Danza Contemporánea", "594"),
                  ("438", "Flamenco", "594"),
                  ("439", "Historia de la Danza", "594"),
                  ("440", "Acrobacia", "594"),
                  ("441", "Canto Aplicado al Arte Dramático", "594"),
                  ("442", "Caracterización e Indumentaria", "594"),
                  ("443", "Danza Aplicada al Arte Dramático", "594"),
                  ("444", "Dicción y Expresión Oral", "594"),
                  ("445", "Dirección Escénica", "594"),
                  ("446", "Dramaturgia", "594"),
                  ("447", "Esgrima", "594"),
                  ("448", "Espacio Escénico", "594"),
                  ("449", "Expresión Corporal", "594"),
                  ("450", "Iluminación", "594"),
                  ("451", "Interpretación", "594"),
                  ("454", "Interpretación en el Teatro del Gesto", "594"),
                  ("455", "Literatura Dramática", "594"),
                  ("456", "Técnicas Escénicas", "594"),
                  ("457", "Técnicas Gráficas", "594"),
                  ("458", "Teoría e Historia del Arte", "594"),
                  ("460", "Lenguaje Musical", "594"),
                  ("501", "Cerámica", "513"),
                  ("502", "Conservación y Restauración de Materiales Arqueológicos", "513"),
                  ("503", "Conservación y Restauración de Obras Escultóricas", "513"),
                  ("504", "Conservación y Restauración de Obras Pictóricas", "513"),
                  ("505", "Conservación y Restauración de Textiles", "513"),
                  ("506", "Conservación y Restauración del Documento Gráfico", "513"),
                  ("507", "Dibujo Artístico y Color", "513"),
                  ("508", "Dibujo Técnico", "513"),
                  ("509", "Diseño de Interiores", "513"),
                  ("510", "Diseño de Moda", "513"),
                  ("511", "Diseño de Productos", "513"),
                  ("512", "Diseño Gráfico", "513"),
                  ("513", "Diseño Textil", "513"),
                  ("514", "Edición de Arte", "513"),
                  ("515", "Fotografía", "513"),
                  ("516", "Historia del Arte", "513"),
                  ("517", "Joyería y Orfebrería", "513"),
                  ("518", "Materiales y Tecnología: Cerámica y Vidrio", "513"),
                  ("519", "Materiales y Tecnología: Conservación y Restauración", "513"),
                  ("520", "Materiales y Tecnología: Diseño", "513"),
                  ("521", "Medios Audiovisuales", "513"),
                  ("522", "Medios Informáticos", "513"),
                  ("523", "Organización Industrial y Legislación", "513"),
                  ("524", "Vidrio", "513"),
                  ("525", "Volumen", "513"),
                  ("501", "Cerámica", "595"),
                  ("502", "Conservación y Restauración de Materiales Arqueológicos", "595"),
                  ("503", "Conservación y Restauración de Obras Escultóricas", "595"),
                  ("504", "Conservación y Restauración de Obras Pictóricas", "595"),
                  ("505", "Conservación y Restauración de Textiles", "595"),
                  ("506", "Conservación y Restauración del Documento Gráfico", "595"),
                  ("507", "Dibujo Artístico y Color", "595"),
                  ("508", "Dibujo Técnico", "595"),
                  ("509", "Diseño de Interiores", "595"),
                  ("510", "Diseño de Moda", "595"),
                  ("511", "Diseño de Productos", "595"),
                  ("512", "Diseño Gráfico", "595"),
                  ("513", "Diseño Textil", "595"),
                  ("514", "Edición de Arte", "595"),
                  ("515", "Fotografía", "595"),
                  ("516", "Historia del Arte", "595"),
                  ("517", "Joyería y Orfebrería", "595"),
                  ("518", "Materiales y Tecnología: Cerámica y Vidrio", "595"),
                  ("519", "Materiales y Tecnología: Conservación y Restauración", "595"),
                  ("520", "Materiales y Tecnología: Diseño", "595"),
                  ("521", "Medios Audiovisuales", "595"),
                  ("522", "Medios Informáticos", "595"),
                  ("523", "Organización Industrial y Legislación", "595"),
                  ("524", "Vidrio", "595"),
                  ("525", "Volumen", "595"),
                  ("601", "Artesanía y Ornamentación con elementos vegetales", "596"),
                  ("602", "Bordados y Encajes", "596"),
                  ("603", "Complementos y Accesorios", "596"),
                  ("604", "Dorado y Policromía", "596"),
                  ("605", "Ebanistería Artística", "596"),
                  ("606", "Encuadernación Artística", "596"),
                  ("607", "Esmaltes", "596"),
                  ("608", "Fotografía y Procesos de Reproducción", "596"),
                  ("609", "Modelismo y Maquetismo", "596"),
                  ("610", "Moldes y Reproducciones", "596"),
                  ("611", "Musivaria", "596"),
                  ("612", "Talla en Piedra y Madera", "596"),
                  ("613", "Técnicas Cerámicas", "596"),
                  ("614", "Técnicas de Grabado y Estampación", "596"),
                  ("615", "Técnicas de Joyería y Bisutería", "596"),
                  ("616", "Técnicas de Orfebrería y Platería", "596"),
                  ("617", "Técnicas de Patronaje y Confección", "596"),
                  ("618", "Técnicas del Metal", "596"),
                  ("619", "Técnicas Murales", "596"),
                  ("620", "Técnicas Textiles", "596"),
                  ("621", "Técnicas Vidrieras", "596"),)
